### ISSUE TITLE
Cannot read property output of undefined

### ISSUE THREAD

**Issue by Itrulia** [palantir/tslint#1192]
### Bug Report (delete this for feature requests)

- __TSLint version__: `3.8.1`
- __TypeScript version__: `1.8.10`
- __Running TSLint via__: Gulp

#### TypeScript code being linted
(also happens with empty .ts/tslint.json files)

with `tslint.json`:

```json
{
  "rules": {
    "class-name": true,
    "curly": true,
    "forin": true,
    "indent": [
      true,
      "spaces"
    ],
    "max-line-length": [
      true,
      140
    ],
    "member-access": true,
    "no-angle-bracket-type-assertion": true,
    "no-any": false,
    "no-arg": true,
    "no-bitwise": true,
    "no-conditional-assignment": true,
    "no-consecutive-blank-lines": false,
    "no-console": [
      true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-construct": true,
    "no-constructor-vars": false,
    "no-debugger": true,
    "no-duplicate-key": true,
    "no-duplicate-variable": true,
    "no-eval": true,
    "no-inferrable-types": false,
    "no-internal-module": true,
    "no-invalid-this": true,
    "no-reference": true,
    "no-require-imports": true,
    "no-shadowed-variable": true,
    "no-string-literal": true,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unreachable": true,
    "no-unused-expression": true,
    "no-unused-variable": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "no-var-requires": true,
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-finally",
      "check-whitespace"
    ],
    "quotemark": [
      true,
      "double",
      "avoid-escape"
    ],
    "radix": true,
    "semicolon": [
      true,
      "always"
    ],
    "switch-default": true,
    "triple-equals": [
      true,
      "allow-null-check",
      "allow-undefined-check"
    ],
    "use-isnan": true,
    "use-strict": [
      true,
      "check-module",
      "check-function"
    ]
  }
}

```

#### Actual behavior

Throwing error

#### Expected behavior

Linting my Typescript files

## Error

	/home/kme/Documents/playQuest/node_modules/map-stream/index.js:103
	        throw err
	        ^

	TypeError: Cannot read property 'output' of undefined
	    at Stream.reportFailures (/home/kme/Documents/playQuest/node_modules/gulp-tslint/index.js:200:46)
	    at Stream.stream.write (/home/kme/Documents/playQuest/node_modules/through/index.js:26:11)
	    at Stream.ondata (stream.js:31:26)
	    at emitOne (events.js:77:13)
	    at Stream.emit (events.js:169:7)
	    at queueData (/home/kme/Documents/playQuest/node_modules/map-stream/index.js:43:21)
	    at next (/home/kme/Documents/playQuest/node_modules/map-stream/index.js:71:7)
	    at /home/kme/Documents/playQuest/node_modules/map-stream/index.js:85:7
	    at /home/kme/Documents/playQuest/node_modules/gulp-tslint/index.js:79:20
	    at wrappedMapper (/home/kme/Documents/playQuest/node_modules/map-stream/index.js:84:19)
	    at Stream.stream.write (/home/kme/Documents/playQuest/node_modules/map-stream/index.js:96:21)
	    at write (/home/kme/Documents/playQuest/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
	    at flow (/home/kme/Documents/playQuest/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
	    at DestroyableTransform.pipeOnReadable (/home/kme/Documents/playQuest/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
	    at emitNone (events.js:67:13)
	    at DestroyableTransform.emit (events.js:166:7)

**Comment by Itrulia** [comment]
Update: I tried to watch a directory...
