### ISSUE TITLE
Release 3.10.0 breaks backward compatibility

### ISSUE THREAD

**Issue by blakeembrey** [palantir/tslint#1243]
The recent release is erroring, feel free to close if you feel it's acceptable - I just wanted to mention it since `3.10.0` is meant to be a backward compatible release: https://github.com/TypeStrong/ts-node/pull/109.

### Bug Report

- __TSLint version__: `3.10.0`
- __TypeScript version__: any
- __Running TSLint via__: CLI

#### Actual behavior

```
/home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/rules/memberOrderingRule.js:210
        this.memberStack[this.memberStack.length - 1].push(node);
                                                     ^
TypeError: Cannot read property 'push' of undefined
    at MemberOrderingWalker.pushMember (/home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/rules/memberOrderingRule.js:210:54)
    at MemberOrderingWalker.visitMethodDeclaration (/home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/rules/memberOrderingRule.js:149:14)
    at MemberOrderingWalker.SyntaxWalker.visitNode (/home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/language/walker/syntaxWalker.js:342:22)
    at /home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/language/walker/syntaxWalker.js:441:63
    at visitEachNode (/home/travis/build/TypeStrong/ts-node/node_modules/typescript/lib/typescript.js:7255:30)
    at Object.forEachChild (/home/travis/build/TypeStrong/ts-node/node_modules/typescript/lib/typescript.js:7357:24)
    at MemberOrderingWalker.SyntaxWalker.walkChildren (/home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/language/walker/syntaxWalker.js:441:12)
    at MemberOrderingWalker.SyntaxWalker.visitObjectLiteralExpression (/home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/language/walker/syntaxWalker.js:148:14)
    at MemberOrderingWalker.SyntaxWalker.visitNode (/home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/language/walker/syntaxWalker.js:363:22)
    at /home/travis/build/TypeStrong/ts-node/node_modules/tslint/lib/language/walker/syntaxWalker.js:441:63
```

#### Expected behavior

Still valid.

**Comment by adidahiya** [comment]
thanks for the report @blakeembrey! we'll try to get a patch out ASAP

**Comment by adidahiya** [comment]
do you know which source file TSLint crashed on?

**Comment by blakeembrey** [comment]
Unfortunately, no. Just know the test failed, haven't gone through to debug why yet. Can only check that tomorrow or this weekend.

**Comment by JKillian** [comment]
Looks like it's failing on https://github.com/TypeStrong/ts-node/blob/master/src/ts-node.ts

I'll try to fix this late tonight, unless you get a chance sooner @adidahiya

**Comment by JKillian** [comment]
Should be fixed and new releases are published. Let me know if you run into any further problems!

**Comment by ianks** [comment]
I still get this issue on 3.10.1. @JKillian

**Comment by JKillian** [comment]
@ianks Could you give an example of code where you get this error?

**Comment by ianks** [comment]
I do not have a code example (I am not sure where to find out where this bug is being caused.

But here is the node object:

```js
{ accessLevel: 2,
  isConstructor: false,
  kind: 1,
  membership: 0,
  node: 
   NodeObject {
     kind: 144,
     pos: 353,
     end: 439,
     flags: 0,
     parent: 
      NodeObject {
        kind: 189,
        pos: 311,
        end: 443,
        flags: 0,
        parent: [Object],
        decorators: undefined,
        name: undefined,
        typeParameters: undefined,
        heritageClauses: [Object],
        members: [Object] },
     decorators: undefined,
     asteriskToken: undefined,
     name: 
      NodeObject {
        kind: 69,
        pos: 353,
        end: 364,
        flags: 0,
        parent: [Circular],
        text: 'render' },
     questionToken: undefined,
     typeParameters: undefined,
     parameters: [ pos: 365, end: 365 ],
     body: 
      NodeObject {
        kind: 195,
        pos: 366,
        end: 439,
        flags: 0,
        parent: [Circular],
        statements: [Object] } } }
```

And the member stack is empty. Here is how I examined the code:

``` js
    MemberOrderingWalker.prototype.pushMember = function (node) {
      try{
        this.memberStack[this.memberStack.length - 1].push(node);
      } catch(e) {
        console.log(node);
        console.log(this.memberStack);
        throw e;
      }
    };
```

**Comment by adidahiya** [comment]
related
