### ISSUE TITLE
UTF8 BOF In tslint.json Causes Exception

### ISSUE THREAD

**Issue by timbrown81** [palantir/tslint#1334]
### Bug Report

- __TSLint version__: `3.11.0`
- __TypeScript version__: `1.8`
- __Running TSLint via__: (please choose one) CLI

#### TypeScript code being linted

```ts
na
```

with `tslint.json` configuration:

```json
{
  "extends": "tslint:latest"
}
```

#### Actual behavior

Receives the following exception:
```
SyntaxError: Unexpected token ?
    at Object.parse (native)
    at loadConfigurationFromPath (C:\.npm-global\node_modules\tslint\lib\configuration.js:91:31)
    at Object.findConfiguration (C:\.npm-global\node_modules\tslint\lib\configuration.js:46:12)
    at processFile (C:\.npm-global\node_modules\tslint\lib\tslint-cli.js:111:41)
    at Array.forEach (native)
    at Object.<anonymous> (C:\.npm-global\node_modules\tslint\lib\tslint-cli.js:128:41)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

#### Expected behavior

To open the configuration file and lint the ts files.  

Work Around: This only occurs when using certain editors, such as VS 2015.  These editors write a BOF to the start of the json file. These need to be stripped prior to parsing to json.  So one workaround is to edit the file using another editor like notepad.

This was originally reported last year, but the issue still arises.  https://github.com/palantir/tslint/pull/703

**Comment by JKillian** [comment]
Looks like the fix from last year got deleted in the midst of lots of other changes. Thanks for reporting this!
