### ISSUE TITLE
3.12.0: TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by sanex3339** [palantir/tslint#1345]
### Bug Report

- __TSLint version__: `3.12.0`
- __TypeScript version__: `1.8.10`
- __Running TSLint via__: `CLI`

after update to 3.12.0 i got a following error when run tslint:
```
/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/tslint/lib/rules/typedefRule.js:134
        var performCheck = !(node.initializer.kind === ts.SyntaxKind.ArrowFunction && node.type == null);


TypeError: Cannot read property 'kind' of undefined
 at TypedefWalker.visitPropertyDeclaration (/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/tslint/lib/rules/typedefRule.js:134:46)
    at TypedefWalker.SyntaxWalker.visitNode (/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/tslint/lib/language/walker/syntaxWalker.js:399:22)
    at /home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/typescript/lib/typescript.js:7255:30)
    at Object.forEachChild (/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/typescript/lib/typescript.js:7484:21)
    at TypedefWalker.SyntaxWalker.walkChildren (/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at TypedefWalker.SyntaxWalker.visitClassDeclaration (/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/tslint/lib/language/walker/syntaxWalker.js:43:14)
    at TypedefWalker.SyntaxWalker.visitNode (/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/tslint/lib/language/walker/syntaxWalker.js:264:22)
    at /home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/home/sanex/PhpstormProjects/javascript-obfuscator/node_modules/typescript/lib/typescript.js:7255:30)
```

config:
```
{
  "rules": {
    ...
    "typedef": [
      true,
      "call-signature",
      "parameter",
      "arrow-parameter",
      "property-declaration",
      "variable-declaration",
      "member-variable-declaration"
    ],
   ...
  }
}
```

**Comment by JKillian** [comment]
Thanks for the report @sanex3339 - can you post a snippet of code that causes this error?

**Comment by sanex3339** [comment]
TSLint check all files under this directory:
https://github.com/sanex3339/javascript-obfuscator/tree/dev/src

**Comment by sanex3339** [comment]
this file
https://github.com/sanex3339/javascript-obfuscator/blob/dev/src/cli/JavaScriptObfuscatorCLI.ts

**Comment by sanex3339** [comment]
and this. Small file.
https://github.com/sanex3339/javascript-obfuscator/blob/dev/src/Options.ts

**Comment by JonathanPorta** [comment]
I am seeing this as well. Stacktrace:
```
TypeError: Cannot read property 'kind' of undefined
    at TypedefWalker.visitPropertyDeclaration (/home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/tslint/lib/rules/typedefRule.js:134:46)
    at TypedefWalker.SyntaxWalker.visitNode (/home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/tslint/lib/language/walker/syntaxWalker.js:399:22)
    at /home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/typescript/lib/typescript.js:7255:30)
    at Object.forEachChild (/home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/typescript/lib/typescript.js:7484:21)
    at TypedefWalker.SyntaxWalker.walkChildren (/home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at TypedefWalker.SyntaxWalker.visitClassDeclaration (/home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/tslint/lib/language/walker/syntaxWalker.js:43:14)
    at TypedefWalker.SyntaxWalker.visitNode (/home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/tslint/lib/language/walker/syntaxWalker.js:264:22)
    at /home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/home/portaj/devel/portaj/mtna/Montana-News-Archive/node_modules/typescript/lib/typescript.js:7255:30)
```

**Comment by JKillian** [comment]
Thanks @sanex3339, I've filed #1346 which should fix this.

**Comment by sanex3339** [comment]
thank you!

**Comment by JonathanPorta** [comment]
Thanks for hopping on this so quick!

**Comment by JKillian** [comment]
New version of TSLint is published, let me know if you run into any other issues!

**Comment by d3viant0ne** [comment]
@JKillian Running into a slightly different variation of this on both the current published version & @next 

```
/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/rules/oneLineRule.js:163
        if (body.kind === ts.SyntaxKind.ModuleBlock) {
                ^

TypeError: Cannot read property 'kind' of undefined
    at OneLineWalker.visitModuleDeclaration (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/rules/oneLine
    at OneLineWalker.SyntaxWalker.visitNode (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/language/walk
    at /Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/typescript/lib/typescript.js:7959:30)
    at Object.forEachChild (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/typescript/lib/typescript.js:8117:24)
    at OneLineWalker.SyntaxWalker.walkChildren (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/language/w
    at OneLineWalker.SyntaxWalker.visitSourceFile (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/languag
    at OneLineWalker.SyntaxWalker.visitNode (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/language/walk
    at OneLineWalker.SyntaxWalker.walk (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/language/walker/sy
    at Rule.AbstractRule.applyWithWalker (/Users/d3viant0ne/Projects/easymetrics/emnext-client/node_modules/tslint/lib/language/rule/ab
```

**Comment by sebastianhaas** [comment]
Same for me. The issue does occur on Travis but not on my local Windows machine. Both running Node 6.

**Comment by JohannesRudolph** [comment]
same  issue here. @d3viant0ne should probably open a new ticket, this one is closed.

**Comment by adidahiya** [comment]
Yeah a new ticket would be nice, as well as an isolated code sample where the linter crashes.

**Comment by d3viant0ne** [comment]
@adidahiya - I'll open a new ticket and get you an isolated example

**Comment by omelhoro** [comment]
I had this issue in the ng2 starter pack using **tslint@3.15.1** and traced the error to that file https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/custom-typings.d.ts

I resolved it by commenting out this line
```typescript
declare module '*';
```

The error stack:
```
/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/rules/oneLineRule.js:163
        if (body.kind === ts.SyntaxKind.ModuleBlock) {
                ^

TypeError: Cannot read property 'kind' of undefined
    at OneLineWalker.visitModuleDeclaration (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/rules/oneLineRule.js:163:17)
    at OneLineWalker.SyntaxWalker.visitNode (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/language/walker/syntaxWalker.js:366:22)
    at /Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/typescript/lib/typescript.js:8251:30)
    at Object.forEachChild (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/typescript/lib/typescript.js:8411:24)
    at OneLineWalker.SyntaxWalker.walkChildren (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at OneLineWalker.SyntaxWalker.visitSourceFile (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/language/walker/syntaxWalker.js:190:14)
    at OneLineWalker.SyntaxWalker.visitNode (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/language/walker/syntaxWalker.js:414:22)
    at OneLineWalker.SyntaxWalker.walk (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/language/walker/syntaxWalker.js:7:14)
    at Rule.AbstractRule.applyWithWalker (/Users/igor/dev/own/lang-project/ld-angular-rx/node_modules/tslint/lib/language/rule/abstractRule.js:19:16)

```

**Comment by adidahiya** [comment]
@omelhoro that looks like #1425

**Comment by Andrey-Pavlov** [comment]
npm install tslint@next helps me
https://github.com/palantir/tslint/issues/1425
