### ISSUE TITLE
TypeError: Cannot read property 'dedent' of undefined

### ISSUE THREAD

**Issue by alexeden** [palantir/tslint#1387]
### Bug Report
- **TSLint version**: `3.13.0`
- **TypeScript version**: `1.8.10`
- **Running TSLint via**: Atom
#### TypeScript code being linted

``` ts
export class AnyClass {
}
```

with `tslint.json` configuration:

``` json
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
    "align": [
      true,
      "parameters",
      "statements",
      "arguments"
    ],
    "comment-format": [
      true,
      "check-space"
    ],
    "component-class-suffix": true,
    "component-selector-name": [
      true,
      "kebab-case"
    ],
    "component-selector-type": [
      true,
      "element"
    ],
    "directive-class-suffix": true,
    "directive-selector-name": [
      true,
      "camelCase"
    ],
    "directive-selector-type": [
      true,
      "attribute"
    ],
    "indent": [
      true,
      "spaces"
    ],
    "no-attribute-parameter-decorator": true,
    "no-conditional-assignment": true,
    "no-duplicate-variable": true,
    "no-empty": true,
    "no-forward-ref": true,
    "no-input-rename": true,
    "no-invalid-this": true,
    "no-namespace": true,
    "no-output-rename": true,
    "no-reference": true,
    "no-shadowed-variable": true,
    "no-unreachable": true,
    "no-unused-expression": true,
    "no-unused-variable": [
      true,
      {
        "ignore-pattern": "^Rx"
      }
    ],
    "no-var-keyword": true,
    "one-variable-per-declaration": true,
    "quotemark": [
      true,
      "single"
    ],
    "semicolon": [
      true,
      "always",
      "ignore-interfaces"
    ],
    "trailing-comma": [
      true,
      {
        "multiline": "never",
        "singleline": "never"
      }
    ],
    "triple-equals": true,
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      },
      {
        "call-signature": "onespace",
        "index-signature": "onespace",
        "parameter": "onespace",
        "property-declaration": "onespace",
        "variable-declaration": "onespace"
      }
    ],
    "use-host-property-decorator": true,
    "use-input-property-decorator": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "use-output-property-decorator": true
  }
}
```
#### Actual behavior

```
TypeError: Cannot read property 'dedent' of undefined
    at /Users/alexeden/projects/frontend-checkout/node_modules/tslint/lib/rules/noNamespaceRule.js:21:421
    at Object.<anonymous> (/Users/alexeden/projects/frontend-checkout/node_modules/tslint/lib/rules/noNamespaceRule.js:38:2)
    at Module._compile (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/alexeden/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at loadRule (/Users/alexeden/projects/frontend-checkout/node_modules/tslint/lib/ruleLoader.js:65:26)
    at findRule (/Users/alexeden/projects/frontend-checkout/node_modules/tslint/lib/ruleLoader.js:38:16)
    at Object.loadRules (/Users/alexeden/projects/frontend-checkout/node_modules/tslint/lib/ruleLoader.js:14:24)
    at Linter.lint (/Users/alexeden/projects/frontend-checkout/node_modules/tslint/lib/tslint.js:25:44)
    at /Users/alexeden/enveq/share/atom/packages/linter-tslint/lib/init.coffee:101:31
```

**Comment by giladgray** [comment]
I'm seeing this too in Atom with the same versions as above.

I disabled `no-namespace` rule and now I get the exact same error but in a later file: `node_modules/tslint/lib/rules/noUnusedNewRule.js:21:290`

**Comment by giladgray** [comment]
@alexeden I fixed it in Atom by ensuring that the correct version was installed where Atom expected it, either globally or locally (based on the `linter-tslint` package settings), and then reloading the editor.
