### ISSUE TITLE
error when handling new Typescript 2 module declaration shorthand

### ISSUE THREAD

**Issue by symbyte** [palantir/tslint#1552]
### Bug Report
- **TSLint version**: `3.15.1`
- **TypeScript version**: `2.0.2`
- **Running TSLint via**: gulp-tslint
#### TypeScript code being linted

``` ts
declare module 'node-uuid/node';
```

with `tslint.json` configuration:

``` json
{
  "rulesDirectory":"node_modules/tslint-eslint-rules/dist/rules",
  "rules": {
    "align": [
      true,
      "parameters",
      "statements"
    ],
    "class-name": true,
    "comment-format": [
      true,
      "check-space"
    ],
    "curly": true,
    "eofline": false,
    "maxlinelength": [
      true,
      80
    ],
    "indent": [
      true,
      "spaces"
    ],
    "interface-name": true,
    "no-duplicate-key": true,
    "no-duplicate-variable": true,
    "no-eval": true,
    "no-extra-semi": true,
    "no-internal-module": true,
    "no-trailing-whitespace": true,
    "no-consecutive-blank-lines": true,
    "no-conditional-assignment": true,
    "no-constant-condition": true,
    "no-switch-case-fallthrough": true,
    "no-string-literal": false,
    "no-require-imports": false,
    "no-var-keyword": true,
    "no-unused-variable": true,
    "no-unreachable": true,
    "no-use-before-declare": true,
    "one-line": [
      true,
      "check-catch",
      "check-else",
      "check-open-brace",
      "check-whitespace"
    ],
    "quotemark": [
      true,
      "single"
    ],
    "semicolon": true,
    "switch-default": false,
    "triple-equals": [
      true,
      "allow-null-check"
    ],
    "typedef": false,
    "variable-name": [
      true,
      "allow-leading-underscore",
      "check-format",
      "allow-leading-underscore",
      "ban-keywords"
    ],
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-module",
      "check-separator",
      "check-type"
    ]
  }
}

```
#### Actual behavior

throws error with this stacktrace: 

```
/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/rules/oneLineRule.js:163
        if (body.kind === ts.SyntaxKind.ModuleBlock) {
                ^

TypeError: Cannot read property 'kind' of undefined
    at OneLineWalker.visitModuleDeclaration (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/rules/oneLineRule.js:163:17)
    at OneLineWalker.SyntaxWalker.visitNode (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/language/walker/syntaxWalker.js:366:22)
    at /Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/Users/stevenchambers/projects/atla/atla-data/node_modules/typescript/lib/typescript.js:8247:30)
    at Object.forEachChild (/Users/stevenchambers/projects/atla/atla-data/node_modules/typescript/lib/typescript.js:8407:24)
    at OneLineWalker.SyntaxWalker.walkChildren (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at OneLineWalker.SyntaxWalker.visitSourceFile (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/language/walker/syntaxWalker.js:190:14)
    at OneLineWalker.SyntaxWalker.visitNode (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/language/walker/syntaxWalker.js:414:22)
    at OneLineWalker.SyntaxWalker.walk (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/language/walker/syntaxWalker.js:7:14)
    at Rule.AbstractRule.applyWithWalker (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/language/rule/abstractRule.js:19:16)
    at Rule.apply (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/rules/oneLineRule.js:21:21)
    at Linter.lint (/Users/stevenchambers/projects/atla/atla-data/node_modules/tslint/lib/tslint.js:68:37)
    at /Users/stevenchambers/projects/atla/atla-data/node_modules/gulp-tslint/index.js:96:34
    at respond (/Users/stevenchambers/projects/atla/atla-data/node_modules/rcloader/index.js:75:7)
    at respond (/Users/stevenchambers/projects/atla/atla-data/node_modules/rcfinder/index.js:140:7)
    at next (/Users/stevenchambers/projects/atla/atla-data/node_modules/rcfinder/index.js:167:16)
```
#### Expected behavior

lint code with no errors.

**Comment by symbyte** [comment]
I was wrong on this. I had assumed that the shorthand was usable inline with your typescript code, but it is only valid syntax for d.ts files

**Comment by JKillian** [comment]
@symbyte Actually, I thought you could use it inline with your code as well. Thanks for the info though!

**Comment by symbyte** [comment]
Actually, you're right. Typescript just views it as a module augmentation. In light of this I'm going to reopen the issue.

**Comment by JKillian** [comment]
@symbyte are you able to try `tslint@v3.15.0-dev.0`? I believe the dev versions of TSLint (which are designed to work with pre-release versions of TS) should have the necessary changes to handle this correctly.

The next TSLint release, 4.0.0 will include all these changes as well.

**Comment by symbyte** [comment]
@JKillian Sure thing! I'll give it a go in the morning and report back.

**Comment by symbyte** [comment]
when i `npm i tslint@v3.15.0-dev.0` it complains about needing a peer dep of tslint@^3. How do I install these two versions at the same time?

**Comment by JKillian** [comment]
@symbyte Sounds like it's some other package doing the complaining, do you know which one it is?

**Comment by prijindal** [comment]
@JKillian In my case it is also complaining about a peer deep of tslint@^3
This is my console output
```
`-- UNMET PEER DEPENDENCY tslint@3.15.0-dev.0 invalid

npm WARN optional Skipping failed optional dependency /chokidar/fs
events:
npm WARN notsup Not compatible with your operating system or archi
tecture: fsevents@1.0.14
npm WARN codelyzer@0.0.28 requires a peer of tslint@^3.9.0 but non
e was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but
none was installed.
npm ERR! code 1
```

**Comment by JKillian** [comment]
Yep, `tslint-loader` doesn't allow `-dev` versions of TSLint. You could get them to change their package.json, or just ignore the NPM errors, everything should still work I think

**Comment by dzonatan** [comment]
Any workarounds to avoid this error and still have such module declaration in `3.15.1`?

**Comment by cvle** [comment]
This prevents using the handy `declare module "*";` declaration which gives all unknown modules a default `any` type. I haven't found a workaround for this yet.

**Comment by cvle** [comment]
I confirm that it works with the `@next` release. I think this can be closed.
