### ISSUE TITLE
Fix for one-line rule only available in "next" version

### ISSUE THREAD

**Issue by iaindurham** [palantir/tslint#1561]
### Bug Report

- __TSLint version__: `3.15.1`
- __TypeScript version__: `2.0.2`
- __Running TSLint via__: CLI

#### TypeScript code being linted

Error occurs before any linting happens

with `tslint.json` configuration:

```json
{
  "extends": "tslint:recommended"
}
```

The `tslint:recommended` rules includes the rule:

```json
"one-line": [true,
        "check-catch",
        "check-else",
        "check-finally",
        "check-open-brace",
        "check-whitespace",
    ],
```

#### Actual behavior

```bash
/Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/rules/oneLineRule.js:163
        if (body.kind === ts.SyntaxKind.ModuleBlock) {
                ^

TypeError: Cannot read property 'kind' of undefined
    at OneLineWalker.visitModuleDeclaration (/Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/rules/oneLineRule.js:163:17)
    at OneLineWalker.SyntaxWalker.visitNode (/Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:366:22)
    at /Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/Users/iaindurham/Sites/amp/components/node_modules/typescript/lib/typescript.js:8247:30)
    at Object.forEachChild (/Users/iaindurham/Sites/amp/components/node_modules/typescript/lib/typescript.js:8407:24)
    at OneLineWalker.SyntaxWalker.walkChildren (/Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at OneLineWalker.SyntaxWalker.visitSourceFile (/Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:190:14)
    at OneLineWalker.SyntaxWalker.visitNode (/Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:414:22)
    at OneLineWalker.SyntaxWalker.walk (/Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:7:14)
    at Rule.AbstractRule.applyWithWalker (/Users/iaindurham/Sites/amp/components/node_modules/tslint/lib/language/rule/abstractRule.js:19:16)
```

#### Expected behavior

It not to error

#### Note

This specific issue was raised in Issue https://github.com/palantir/tslint/issues/1425 and then fixed PR https://github.com/palantir/tslint/pull/1429 but this change is currently only available in the 'next' build. This is fine for my local environment if I specifically install the next version with `npm i tslint@next` but I can't do this on my CI environment or anywhere else that just does an npm install of what is in the package.json.

Is it possible / when will, the changes in PR https://github.com/palantir/tslint/pull/1429 be made available in a non-next version?

I'm only raising this as an issue because the one-line rule is in the `tslint:recommended` rules which ships by default with the non-next version of the code.

**Comment by JKillian** [comment]
The changes in #1429 will be available in the next TSLint release, which will be 4.0. Unfortunately, I can't give you a timeline when that will be, although hopefully within the next few weeks

**Comment by iaindurham** [comment]
@JKillian Thanks for the update. 

Will make a change in my code until the next version is out. Thanks for your prompt response.
