### ISSUE TITLE
Cannot run custom typed rules in the CLI

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#1637]
### Bug Report
- **TSLint version**: `3.15.1`
- **TypeScript version**: `2.0.3`
- **Running TSLint via**: CLI
#### tslint.json

_test.json_:

``` json
{
    "rules": {
        "my-typed-rule": true
    }
}
```
#### Expected behavior

``` cmd
tslint --project test.json --type-check true --rules-dir src/rules

> (tslint output from my-custom-rule)
```
#### Actual behavior

``` cmd
tslint --project test.json --type-check true --rules-dir src/rules

Error: my-custom-rule requires type checking
    at Rule.TypedRule.apply (C:\Code\tslint-test\node_modules\tslint\lib\language\rule\typedRule.js:15:15)
    at Linter.lint (C:\Users\jogol\AppData\Roaming\npm\node_modules\tslint\lib\tslint.js:69:37)
    at processFile (C:\Users\jogol\AppData\Roaming\npm\node_modules\tslint\lib\tslint-cli.js:138:29)
    at C:\Users\jogol\AppData\Roaming\npm\node_modules\tslint\lib\tslint-cli.js:177:74
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\jogol\AppData\Roaming\npm\node_modules\tslint\lib\tslint-cli.js:177:41)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by JoshuaKGoldberg** [comment]
I think the issue causing this is in `tslintMulti.ts`, where it checks if a rule is a TypedRule:

```ts
if (this.program && rule instanceof TypedRule) {
```

In my call stack the `TypedRule` can be the one defined in `C:\Code\tslint-test\node_modules\tslint` **or** `C:\Users\jogol\AppData\Roaming\npm\node_modules\tslint`.

A couple solution proposals:
* Make a `isTypedRule` equivalent in the class? *(I think preferable, for future compability)*
* Check the `constructor.name` *(I think less preferable)*

**Comment by JoshuaKGoldberg** [comment]
Works for me!
