### ISSUE TITLE
no-unused-variable and destructuring

### ISSUE THREAD

**Issue by kourge** [palantir/tslint#1641]
### Bug Report

- __TSLint version__: `3.13.0`
- __TypeScript version__: `2.0.2`
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
interface F {
  range: {
    start: number;
    end: number;
  };
}

function f({range: {start, end}}: F): number {
  return end - start;
}
```

with `tslint.json` configuration:

```json
{
  "rules": {
    "no-unused-variable": true
  }
}
```

#### Actual behavior

```
/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:49881
            var flags = symbol.flags;
                              ^

TypeError: Cannot read property 'flags' of undefined
    at displayPartKind (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:49881:31)
    at symbolPart (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:49879:34)
    at Object.writeSymbol (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:49866:31)
    at buildBindingElementDisplay (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:18771:28)
    at /Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:18752:110
    at buildDisplayForCommaSeparatedList (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:18798:21)
    at buildBindingPatternDisplay (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:18752:21)
    at buildParameterDisplay (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:18736:21)
    at buildDisplayForParametersAndDelimiters (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:18826:21)
    at Object.buildSignatureDisplay (/Users/kourge/projects/urbandoor/web-app/node_modules/typescript/lib/typescript.js:18872:17)
```

#### Expected behavior

No error.

#### Additional notes

This error does not happen if any of the following is true:
- The function is exported
- The second-level destructuring is removed

**Comment by adidahiya** [comment]
the rule doesn't do very well on nested destructuring. related: https://github.com/palantir/tslint/issues/1606

we're deprecating the rule in v4.0 anyway, see https://github.com/palantir/tslint/issues/1481. I suggest you move to using those compiler options.

**Comment by andy-ms** [comment]
Should be fixed by #2235.

**Comment by corydeppen** [comment]
I'm seeing the `Cannot read property 'flags' of undefined` error when the `no-unused-variable` rule is used with tslint 5.4.3 and tsc 2.4.1. If I remove that rule I no longer see the error.

**Comment by victornoel** [comment]
@corydeppen you should open another issue, there is many reason for this error to be printed.
Also see #3001
