### ISSUE TITLE
one-line rule error in typescript > 2.0

### ISSUE THREAD

**Issue by jmlopez-rod** [palantir/tslint#1722]
### Bug Report

- __TSLint version__: `3.15.1`
- __TypeScript version__: `2.0.6`
- __Running TSLint via__: (please choose one) CLI

#### TypeScript code being linted

```ts
declare module 'mod1';
```

with `tslint.json` configuration:

```json
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-finally",
      "check-whitespace"
    ],
```

#### Actual behavior

```
$ tslint tmp.ts
node_modules/tslint/lib/rules/oneLineRule.js:163
if (body.kind === ts.SyntaxKind.ModuleBlock) {
^

  TypeError: Cannot read property 'kind' of undefined
  at OneLineWalker.visitModuleDeclaration (node_modules/tslint/lib/rules/oneLineRule.js:163:17)
  at OneLineWalker.SyntaxWalker.visitNode (node_modules/tslint/lib/language/walker/syntaxWalker.js:366:22)
  at node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
  at visitEachNode (node_modules/typescript/lib/typescript.js:8338:30)
  at Object.forEachChild (node_modules/typescript/lib/typescript.js:8498:24)
  at OneLineWalker.SyntaxWalker.walkChildren (node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
  at OneLineWalker.SyntaxWalker.visitSourceFile (node_modules/tslint/lib/language/walker/syntaxWalker.js:190:14)
  at OneLineWalker.SyntaxWalker.visitNode (node_modules/tslint/lib/language/walker/syntaxWalker.js:414:22)
  at OneLineWalker.SyntaxWalker.walk (node_modules/tslint/lib/language/walker/syntaxWalker.js:7:14)
  at Rule.AbstractRule.applyWithWalker (node_modules/tslint/lib/language/rule/abstractRule.js:19:16)

```

#### Expected behavior

Should not crash. In typescript 2.0 we can declare modules without a block:
https://www.typescriptlang.org/docs/release-notes/typescript-2.0.html#shorthand-ambient-module-declarations

**Comment by jmlopez-rod** [comment]
Duplicate and already fixed: https://github.com/palantir/tslint/issues/1425
