### ISSUE TITLE
Using destructuring throws: "Cannot read property 'flags' of undefined"

### ISSUE THREAD

**Issue by tomitrescak** [palantir/tslint#1774]
### Bug Report

- __TSLint version__: `4.0.1`
- __TypeScript version__: `2.1.0.dev`
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
export const SchedulePractical = ({ field, deleteField }: any, { Binder: { bindTo } }: App.Context ) => (
  <Form.Group>
    <ReduxForm.DatePicker model={bindTo(field, 'from')} placeholder={i18n`Visible From`} width={3} />
    <ReduxForm.DatePicker model={bindTo(field, 'due')} placeholder={i18n`Due Date`} width={3} />
    <ReduxForm.Input readOnly model={bindTo(field, 'name')} width={7} />
    <Form.Button type="button" width={3} onClick={() => deleteField(field)} color="red" icon="trash" />
  </Form.Group>
);
```

with `tslint.json` configuration:

```json
{
  "rules": {
    "class-name": true,
    "comment-format": [true, "check-space"],
    "curly": true,
    "eofline": true,
    "forin": false,
    "indent": [true, "spaces"],
    "label-position": true,
    "max-line-length": [false, 140],
    "member-access": false,
    "member-ordering": [true,
      "public-before-private",
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-arg": true,
    "no-bitwise": true,
    "no-console": [true,
      "log",
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-variable": true,
    "no-empty": true,
    "no-eval": false,
    "no-inferrable-types": true,
    "no-shadowed-variable": true,
    "no-string-literal": false,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "object-literal-sort-keys": false,
    "one-line": [true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
    "quotemark": [true, "single", "jsx-double", "avoid-escape"],
    "radix": true,
    "semicolon": [true],
    "triple-equals": [true, "allow-null-check"],
    "typedef-whitespace": [true, {
      "call-signature": "nospace",
      "index-signature": "nospace",
      "parameter": "nospace",
      "property-declaration": "nospace",
      "variable-declaration": "nospace"
    }],
    "variable-name": false,
    "whitespace": [true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ]
  }
}
```

#### Actual behavior

This bit `{ Binder: { bindTo } }` is responsible for the following error.

Throws: 

```
 tslint ./app/client/modules/schedules/components/schedule_admin_view.tsx
/usr/local/lib/node_modules/typescript/lib/typescript.js:61677
            var flags = symbol.flags;
                              ^

TypeError: Cannot read property 'flags' of undefined
    at displayPartKind (/usr/local/lib/node_modules/typescript/lib/typescript.js:61677:31)
    at symbolPart (/usr/local/lib/node_modules/typescript/lib/typescript.js:61675:34)
    at Object.writeSymbol (/usr/local/lib/node_modules/typescript/lib/typescript.js:61662:31)
    at buildBindingElementDisplay (/usr/local/lib/node_modules/typescript/lib/typescript.js:24826:28)
    at /usr/local/lib/node_modules/typescript/lib/typescript.js:24807:110
    at buildDisplayForCommaSeparatedList (/usr/local/lib/node_modules/typescript/lib/typescript.js:24853:21)
    at buildBindingPatternDisplay (/usr/local/lib/node_modules/typescript/lib/typescript.js:24807:21)
    at buildParameterDisplay (/usr/local/lib/node_modules/typescript/lib/typescript.js:24791:21)
    at buildDisplayForParametersAndDelimiters (/usr/local/lib/node_modules/typescript/lib/typescript.js:2488
```

#### Expected behavior

No errors

**Comment by nchen63** [comment]
fails on `no-use-before-declare` rule when calling TypeScript API languageService on `SchedulePractical` in sample code

**Comment by nchen63** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/12451
