### ISSUE TITLE
CLI --fix --test always fails

### ISSUE THREAD

**Issue by rbellamy** [palantir/tslint#1829]
### Bug Report

- __TSLint version__: `4.0.2`
- __TypeScript version__: `1.8.3` `2.0.10` `2.0.9`
- __Running TSLint via__: CLI

#### TypeScript code being linted

Trying to `tslint --fix` my `./src` directory and files.

with `tsconfig.json` configuration:

```json
"exclude": [
    "node_modules",
    "dist",
    "typings/custom"
  ]
```

#### Actual behavior

When adding the `--test` switch, paths to config and files start failing.
```bash
# THIS WORKS
2016-12-07 08:03:53
rbellamy@eanna i ~/Development/Terradatum/aergo/aergo-client master % tslint -c ./tslint.json --fix ./src/**/*.ts
# THIS FAILS
2016-12-07 08:04:20
rbellamy@eanna i ~/Development/Terradatum/aergo/aergo-client master % tslint -c ./tslint.json --fix --test ./src/**/*.ts
/usr/lib/node_modules/tslint/lib/configuration.js:114
            throw new Error("Could not find config file at: " + path.resolve(suppliedConfigFilePath));
            ^

Error: Could not find config file at: /home/rbellamy/Development/Terradatum/aergo/aergo-client/src/actions/account/account.action-creators.ts/tslint.json
    at findConfigurationPath (/usr/lib/node_modules/tslint/lib/configuration.js:114:19)
    at Function.findConfiguration (/usr/lib/node_modules/tslint/lib/configuration.js:90:16)
    at Object.runTest (/usr/lib/node_modules/tslint/lib/test.js:32:31)
    at Object.<anonymous> (/usr/lib/node_modules/tslint/lib/tslint-cli.js:121:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

# THIS WORKS
2016-12-07 07:57:33
rbellamy@eanna i ~/Development/Terradatum/aergo/aergo-client master % tslint --project ./tsconfig.json --fix 
# THIS FAILS
2016-12-07 07:57:33
rbellamy@eanna i ~/Development/Terradatum/aergo/aergo-client master % tslint --project ./tsconfig.json --test --fix
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.runTest (/usr/lib/node_modules/tslint/lib/test.js:31:38)
    at Object.<anonymous> (/usr/lib/node_modules/tslint/lib/tslint-cli.js:121:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
# NEITHER OF THESE WORK
2016-12-07 08:04:26
rbellamy@eanna i ~/Development/Terradatum/aergo/aergo-client master % tslint --fix --test              
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.runTest (/usr/lib/node_modules/tslint/lib/test.js:31:38)
    at Object.<anonymous> (/usr/lib/node_modules/tslint/lib/tslint-cli.js:121:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
zsh: exit 1     tslint --fix --test
2016-12-07 08:06:28
rbellamy@eanna i ~/Development/Terradatum/aergo/aergo-client master % tslint --fix . # IMMEDIATELY RETURNS
```

#### Expected behavior

`--fix --test` should allow me to see what will be modified - I should be able to point to either `--config` and/or `--project` when testing fixes.

**Comment by adidahiya** [comment]
That's not quite what `--test` does... If we did add a "dry run" option, we would make the CLI option `--dry-run`. See the longer form description of `--test` in the README:

```
    Runs tslint on the specified directory and checks if tslint's output matches
    the expected output in .lint files. Automatically loads the tslint.json file in the
    specified directory as the configuration file for the tests. See the
    full tslint documentation for more details on how this can be used to test custom rules.
```

We use this to verify TSLint itself, not for dry runs of the auto fixer.

**Comment by rbellamy** [comment]
That makes perfect sense. Sorry for the noise.
