### ISSUE TITLE
objectLiteralKeyQuotesRule: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by cvle** [palantir/tslint#1918]
### Bug Report

- __TSLint version__: `4.2.0`
- __TypeScript version__: `2.1.4`
- __Running TSLint via__: gulp-tslint 7.0.1

tslint.json:

~~~json
{
  "extends": "tslint:recommended",
  "rules": {
    "interface-name": [true, "never-prefix"],
    "object-literal-sort-keys": false,
    "forin": false,
    "no-string-literal": false,
    "file-header": [true, "@license"],
    "no-switch-case-fall-through": true,
    "max-classes-per-file": false,
    "object-literal-key-quotes": [true, "as-needed"],
    "ordered-imports": false,
    "max-classes-per-file": false,
    "no-unused-variable": [true, "react", {
      "ignore-pattern": "^_"
    }],
    "variable-name": [true,
      "ban-keywords", "check-format", "allow-leading-underscore", "allow-pascal-case"
    ]
  }
}
~~~

After updating to 4.2.0 linting fails with:

~~~
/home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/rules/objectLiteralKeyQuotesRule.js:107
            if (name_2.kind === ts.SyntaxKind.StringLiteral && (noneNeedQuotes || !propertyNeedsQuotes(name_2.text))) {
                      ^
TypeError: Cannot read property 'kind' of undefined
    at ObjectLiteralKeyQuotesWalker.noneMayHaveQuotes (/home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/rules/objectLiteralKeyQuotesRule.js:107:23)
    at ObjectLiteralKeyQuotesWalker.visitObjectLiteralExpression (/home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/rules/objectLiteralKeyQuotesRule.js:73:22)
    at ObjectLiteralKeyQuotesWalker.SyntaxWalker.visitNode (/home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/language/walker/syntaxWalker.js:430:22)
    at /home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/language/walker/syntaxWalker.js:517:63
    at visitNode (/home/travis/build/wikiwi/react-css-transition/node_modules/typescript/lib/typescript.js:13895:20)
    at Object.forEachChild (/home/travis/build/wikiwi/react-css-transition/node_modules/typescript/lib/typescript.js:13957:21)
    at ObjectLiteralKeyQuotesWalker.SyntaxWalker.walkChildren (/home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/language/walker/syntaxWalker.js:517:12)
    at ObjectLiteralKeyQuotesWalker.SyntaxWalker.visitVariableDeclaration (/home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/language/walker/syntaxWalker.js:251:14)
    at ObjectLiteralKeyQuotesWalker.SyntaxWalker.visitNode (/home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/language/walker/syntaxWalker.js:496:22)
    at /home/travis/build/wikiwi/react-css-transition/node_modules/tslint/lib/language/walker/syntaxWalker.js:517:63
~~~

See build log: https://travis-ci.org/wikiwi/react-css-transition/builds/186315311

**Comment by nchen63** [comment]
This is probably fixed by #1917

**Comment by eamodio** [comment]
I'm running into the same issue on v4.2.0

**Comment by nascosto** [comment]
Just hit this issue.

**Comment by mohsen1** [comment]
You can turn off this rule in your `teslint.json` until fix is released:

```json
// temporarely trurned off due to https://github.com/palantir/tslint/issues/1918
    "object-literal-key-quotes": false,
```

**Comment by JoshuaKGoldberg** [comment]
Still seeing it on 5.0.0. Default config and all.
