### ISSUE TITLE
4.4.1: `formatter ' json' not found` (TS 2.1.5 & WebStorm)

### ISSUE THREAD

**Issue by JD-Robbs** [palantir/tslint#2130]
### Bug Report

- __TSLint version__: `4.4.1`
- __TypeScript version__: `2.1.5`
- __Running TSLint via__: WebStorm

#### TypeScript code being linted

```ts
n/a
```

with `tslint.json` configuration:

```json
n/a
```

#### Actual behavior
    2017-01-26 07:59:38,157 [ 368336]   INFO - avascript.linter.tslint.TsLint - TsLint inner error. TsLint version: 4.4.1
    
    C:\r\node_modules\tslint\lib\runner.js:117
    throw error;
    ^
    
    Error: formatter ' json' not found
    at Linter.getResult (C:\r\node_modules\tslint\lib\linter.js:121:19)
    at Runner.processFiles (C:\r\node_modules\tslint\lib\runner.js:156:33)
    at Runner.run (C:\r\node_modules\tslint\lib\runner.js:109:18)
    at Object.<anonymous> (C:\r\node_modules\tslint\lib\tslint-cli.js:138:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

#### Expected behavior

`tslint` crashes in WebStorm when opening any `.ts` file since updating to 4.4.1.  It looks like the `json` formatter is preceded by a stray whitespace - perhaps that's the cause? Or it's an issue with WebStorm, in which case let's close.

**Comment by nanocloudx** [comment]
I also confirmed a similar problem.
It did not occur in v4.3.1, it occurred in v4.4.1.

**Comment by vaclavbohac** [comment]
I have the same problem
