### ISSUE TITLE
Error "Cannot read property 'name' of undefined" with `no-floating-promises` rule enabled

### ISSUE THREAD

**Issue by chrismbarr** [palantir/tslint#2133]
### Bug Report

- __TSLint version__: `4.4.1`
- __TypeScript version__: `2.1.5`
- __Running TSLint via__: gulp-tslint `7.0.1`

with `tslint.json` configuration:

```json
"no-floating-promises": true,
```

#### Actual behavior
This error is thrown
```
[07:42:23] Using gulpfile C:\<my-project>\gulpfile.js
[07:42:23] Starting 'lint'...
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Cannot read property 'name' of undefined
    at getSignatureFromDeclaration (C:\<my-project>\node_modules\typescript\lib\typescript.js:28873:47)
    at getThisTypeOfDeclaration (C:\<my-project>\node_modules\typescript\lib\typescript.js:27447:43)
    at checkThisExpression (C:\<my-project>\node_modules\typescript\lib\typescript.js:34029:32)
    at checkExpressionWorker (C:\<my-project>\node_modules\typescript\lib\typescript.js:38187:28)
    at checkExpression (C:\<my-project>\node_modules\typescript\lib\typescript.js:38165:42)
    at checkNonNullExpression (C:\<my-project>\node_modules\typescript\lib\typescript.js:35540:24)
    at checkPropertyAccessExpressionOrQualifiedName (C:\<my-project>\node_modules\typescript\lib\typescript.js:35587:24)
    at checkPropertyAccessExpression (C:\<my-project>\node_modules\typescript\lib\typescript.js:35554:20)
    at checkExpressionWorker (C:\<my-project>\node_modules\typescript\lib\typescript.js:38208:28)
    at checkExpression (C:\<my-project>\node_modules\typescript\lib\typescript.js:38165:42)
```

#### Expected behavior

No error to be thrown.  When `"no-floating-promises": false` I get no errors.

#### Note
I consistently get this exact error with rules that require type info _(I've [opened an issue with gulp-tslint](https://github.com/panuhorsmalahti/gulp-tslint/issues/105) about this)_, so I just leave those rules off for now.  However, [the docs for this particular rule](https://palantir.github.io/tslint/rules/no-floating-promises/) make no mention of type info being required.  If this rule **does** require type info, perhaps only the docs need to be updated.

**Comment by JoshuaKGoldberg** [comment]
Interesting that the docs don't mention that it requires type info. The rule metadata indicates it does.

https://github.com/palantir/tslint/blob/67732d625069f104a0e9efd755a95e5369313966/src/rules/noFloatingPromisesRule.ts#L41
