### ISSUE TITLE
kind of undefined in canHaveLeadingTrivia

### ISSUE THREAD

**Issue by Pajn** [palantir/tslint#2330]
### Bug Report

- __TSLint version__: 4.5.1
- __TypeScript version__: 2.2.1
- __Running TSLint via__: (pick one) VSCode

#### TypeScript code being linted
No minimal case, but I don't think it's needed here.

#### Actual behavior
```
TypeError: Cannot read property 'kind' of undefined
    at canHaveLeadingTrivia (/home/rasmus/Development/control-flow/ts/node_modules/tsutils/src/utils.js:309:26)
    at /home/rasmus/Development/control-flow/ts/node_modules/tsutils/src/utils.js:283:23
    at iterate (/home/rasmus/Development/control-flow/ts/node_modules/tsutils/src/utils.js:251:20)
    at Array.forEach (native)
    at iterate (/home/rasmus/Development/control-flow/ts/node_modules/tsutils/src/utils.js:253:50)
    at Array.forEach (native)
    at iterate (/home/rasmus/Development/control-flow/ts/node_modules/tsutils/src/utils.js:253:50)
    at forEachToken (/home/rasmus/Development/control-flow/ts/node_modules/tsutils/src/utils.js:254:7)
    at Object.forEachComment (/home/rasmus/Development/control-flow/ts/node_modules/tsutils/src/utils.js:282:12)
    at EnableDisableRulesWalker.getEnableDisableRuleMap (/home/rasmus/Development/control-flow/ts/node_modules/tslint/lib/enableDisableRules.js:42:15)
```

The line `if (parent.parent.kind === ts.SyntaxKind.JsxClosingElement)` in `canHaveLeadingTrivia` must guard for the node not having grandparents, something like `if (parent.parent && parent.parent.kind === ts.SyntaxKind.JsxClosingElement)`

**Comment by ajafff** [comment]
`parent.parent.kind` was actually a bug and should have been `parent.kind`.
I just released `tsutils@1.3.0` which includes this fix.

I couldn't reproduce the error. Can you share a code snipped that could be used as a regression test?

**Comment by Pajn** [comment]
Great!

> Can you share a code snipped that could be used as a regression test?

Sorry, I saw it in the logs in a larger project with format on save when I tried to investigated why format all (and therefore format on save) rarely works however I don't get it now. I might be able to reproduce it by jumping to older commits if there is some way I can see in at least which file it occurred?

**Comment by ajafff** [comment]
That's exactly what I was looking for.
While we cannot guarantee useful results from linting invalid source code, we at least try not to crash.
