### ISSUE TITLE
use the 1.4 compiler

### ISSUE THREAD

**Issue by ashwinr** [palantir/tslint#260]

**Comment by JeroMiya** [comment]
I attempted to replace the compiler service with the 1.4.1 version and got this error log:

```

> tslint@1.2.0 test F:\github\tslint
> grunt

[4mRunning "clean:core" (clean) task[24m
Cleaning build/rules/...[32mOK[39m
Cleaning build/formatters...[32mOK[39m
Cleaning lib/tslint.d.ts...[32mOK[39m
Cleaning lib/tslint.js...[32mOK[39m

[4mRunning "ts:core" (ts) task[24m
[33mCompiling...[39m
[36mCleared fast compile cache for target: core[39m
[36mFast compile will not work when --out is specified. Ignoring fast compilation[39m
Using tsc v1.3.0



[32mTypeScript compilation complete: 1.19s for 1 typescript files[39m

[4mRunning "concat:core" (concat) task[24m
File lib/tslint.js created.

[4mRunning "ts:core_rules" (ts) task[24m
[33mCompiling...[39m
[36m### Fast Compile >>lib/tslint.d.ts[39m
[36m### Fast Compile >>src/rules/banRule.ts[39m
[36m### Fast Compile >>src/rules/classNameRule.ts[39m
[36m### Fast Compile >>src/rules/commentFormatRule.ts[39m
[36m### Fast Compile >>src/rules/curlyRule.ts[39m
[36m### Fast Compile >>src/rules/eoflineRule.ts[39m
[36m### Fast Compile >>src/rules/forinRule.ts[39m
[36m### Fast Compile >>src/rules/indentRule.ts[39m
[36m### Fast Compile >>src/rules/interfaceNameRule.ts[39m
[36m### Fast Compile >>src/rules/jsdocFormatRule.ts[39m
[36m### Fast Compile >>src/rules/labelPositionRule.ts[39m
[36m### Fast Compile >>src/rules/labelUndefinedRule.ts[39m
[36m### Fast Compile >>src/rules/maxLineLengthRule.ts[39m
[36m### Fast Compile >>src/rules/memberOrderingRule.ts[39m
[36m### Fast Compile >>src/rules/noAnyRule.ts[39m
[36m### Fast Compile >>src/rules/noArgRule.ts[39m
[36m### Fast Compile >>src/rules/noBitwiseRule.ts[39m
[36m### Fast Compile >>src/rules/noConsecutiveBlankLinesRule.ts[39m
[36m### Fast Compile >>src/rules/noConsoleRule.ts[39m
[36m### Fast Compile >>src/rules/noConstructRule.ts[39m
[36m### Fast Compile >>src/rules/noConstructorVarsRule.ts[39m
[36m### Fast Compile >>src/rules/noDebuggerRule.ts[39m
[36m### Fast Compile >>src/rules/noDuplicateKeyRule.ts[39m
[36m### Fast Compile >>src/rules/noDuplicateVariableRule.ts[39m
[36m### Fast Compile >>src/rules/noEmptyRule.ts[39m
[36m### Fast Compile >>src/rules/noEvalRule.ts[39m
[36m### Fast Compile >>src/rules/noStringLiteralRule.ts[39m
[36m### Fast Compile >>src/rules/noSwitchCaseFallThroughRule.ts[39m
[36m### Fast Compile >>src/rules/noTrailingCommaRule.ts[39m
[36m### Fast Compile >>src/rules/noTrailingWhitespaceRule.ts[39m
[36m### Fast Compile >>src/rules/noUnreachableRule.ts[39m
[36m### Fast Compile >>src/rules/noUnusedExpressionRule.ts[39m
[36m### Fast Compile >>src/rules/noUnusedVariableRule.ts[39m
[36m### Fast Compile >>src/rules/noUseBeforeDeclareRule.ts[39m
[36m### Fast Compile >>src/rules/noVarRequiresRule.ts[39m
[36m### Fast Compile >>src/rules/oneLineRule.ts[39m
[36m### Fast Compile >>src/rules/quotemarkRule.ts[39m
[36m### Fast Compile >>src/rules/radixRule.ts[39m
[36m### Fast Compile >>src/rules/semicolonRule.ts[39m
[36m### Fast Compile >>src/rules/tripleEqualsRule.ts[39m
[36m### Fast Compile >>src/rules/typedefRule.ts[39m
[36m### Fast Compile >>src/rules/typedefWhitespaceRule.ts[39m
[36m### Fast Compile >>src/rules/useStrictRule.ts[39m
[36m### Fast Compile >>src/rules/variableNameRule.ts[39m
[36m### Fast Compile >>src/rules/whitespaceRule.ts[39m
Using tsc v1.3.0
F:/github/tslint/src/rules/typedefRule.ts(31,95): error TS2339: Property 'propertyName' does not exist on type 'ISyntaxElement'.

[32m>> [39m1 non-emit-preventing type warning  
[32m>> [39mType errors only.

[32mTypeScript compilation complete: 1.36s for 45 typescript files[39m

[4mRunning "ts:core_formatters" (ts) task[24m
[33mCompiling...[39m
[36mCleared fast compile cache for target: core_formatters[39m
[36m### Fast Compile >>lib/tslint.d.ts[39m
[36m### Fast Compile >>src/formatters/jsonFormatter.ts[39m
[36m### Fast Compile >>src/formatters/pmdFormatter.ts[39m
[36m### Fast Compile >>src/formatters/proseFormatter.ts[39m
[36m### Fast Compile >>src/formatters/verboseFormatter.ts[39m
Using tsc v1.3.0



[32mTypeScript compilation complete: 0.96s for 5 typescript files[39m

[4mRunning "clean:bin" (clean) task[24m
Cleaning bin/tslint-cli.js...[32mOK[39m

[4mRunning "ts:bin" (ts) task[24m
[33mCompiling...[39m
[36mCleared fast compile cache for target: bin[39m
[36mFast compile will not work when --out is specified. Ignoring fast compilation[39m
Using tsc v1.3.0



[32mTypeScript compilation complete: 1.02s for 1 typescript files[39m

[4mRunning "tslint:src" (tslint) task[24m
[32m>> [39m64 files lint free.

[4mRunning "concat:bin" (concat) task[24m
File bin/tslint-cli.js created.

[4mRunning "clean:test" (clean) task[24m

[4mRunning "ts:test" (ts) task[24m
[33mCompiling...[39m
[36mCleared fast compile cache for target: test[39m
[36mFast compile will not work when --out is specified. Ignoring fast compilation[39m
Using tsc v1.3.0



[32mTypeScript compilation complete: 1.36s for 56 typescript files[39m

[4mRunning "tslint:test" (tslint) task[24m
[32m>> [39m53 files lint free.

[4mRunning "concat:test" (concat) task[24m
File build/tslint-tests.js created.

[4mRunning "mochaTest:test" (mochaTest) task[24m
[31m>> [39mMocha exploded!
[31m>> [39mTypeError: Cannot read property 'prototype' of undefined[31m
>> [39m    at __extends (F:\github\tslint\build\tslint-tests.js:26381:21)[31m
>> [39m    at F:\github\tslint\build\tslint-tests.js:26387:9[31m
>> [39m    at Lint (F:\github\tslint\build\tslint-tests.js:26460:7)[31m
>> [39m    at Object.<anonymous> (F:\github\tslint\build\tslint-tests.js:26462:3)[31m
>> [39m    at Module._compile (module.js:456:26)[31m
>> [39m    at Object.Module._extensions..js (module.js:474:10)[31m
>> [39m    at Module.load (module.js:356:32)[31m
>> [39m    at Function.Module._load (module.js:312:12)[31m
>> [39m    at Module.require (module.js:364:17)[31m
>> [39m    at require (module.js:380:17)[31m
>> [39m    at F:\github\tslint\node_modules\grunt-mocha-test\node_modules\mocha\lib\mocha.js:152:27[31m
>> [39m    at Array.forEach (native)[31m
>> [39m    at Mocha.loadFiles (F:\github\tslint\node_modules\grunt-mocha-test\node_modules\mocha\lib\mocha.js:149:14)[31m
>> [39m    at MochaWrapper.run (F:\github\tslint\node_modules\grunt-mocha-test\tasks\lib\MochaWrapper.js:41:15)[31m
>> [39m    at F:\github\tslint\node_modules\grunt-mocha-test\tasks\mocha.js:64:20[31m
>> [39m    at capture (F:\github\tslint\node_modules\grunt-mocha-test\tasks\mocha.js:27:5)[31m
>> [39m    at Object.<anonymous> (F:\github\tslint\node_modules\grunt-mocha-test\tasks\mocha.js:59:5)[31m
>> [39m    at Object.<anonymous> (F:\github\tslint\node_modules\grunt\lib\grunt\task.js:264:15)[31m
>> [39m    at Object.thisTask.fn (F:\github\tslint\node_modules\grunt\lib\grunt\task.js:82:16)[31m
>> [39m    at Object.<anonymous> (F:\github\tslint\node_modules\grunt\lib\util\task.js:301:30)[31m
>> [39m    at Task.runTaskFn (F:\github\tslint\node_modules\grunt\lib\util\task.js:251:24)[31m
>> [39m    at Task.<anonymous> (F:\github\tslint\node_modules\grunt\lib\util\task.js:300:12)[31m
>> [39m    at F:\github\tslint\node_modules\grunt\lib\util\task.js:227:11[31m
>> [39m    at process._tickDomainCallback (node.js:486:13)
[33mWarning: Task "mochaTest:test" failed.  Use --force to continue.[39m

[31mAborted due to warnings.[39m

```

**Comment by JeroMiya** [comment]
It appears TypeScript.SyntaxWalker was removed in 1.4.x.

**Comment by ashwinr** [comment]
yeah, filed https://github.com/Microsoft/TypeScript/issues/1728 for comments

**Comment by gscshoyru** [comment]
This is done, and merged into master -- we'll be publishing the new version to npm (and updating eclipse-tslint and grunt-tslint) on Monday.
