### ISSUE TITLE
applyWithFunction is not a function

### ISSUE THREAD

**Issue by unional** [palantir/tslint#2747]
with tslint 5.2.0

```sh
[Info  - 6:57:53 PM] vscode-tslint: 'this.applyWithFunction is not a function' while validating: /Users/hwong/github/unional/global-store/src/index.ts stacktrace: TypeError: this.applyWithFunction is not a function
    at Rule.apply (/Users/hwong/github/unional/global-store/node_modules/tslint/lib/rules/noIrregularWhitespaceRule.js:27:21)
    at Linter.applyRule (/Users/hwong/github/unional/global-store/node_modules/tslint/lib/linter.js:143:33)
```

Cross post from https://github.com/Microsoft/vscode-tslint/issues/205
Could be `tslint` issue.

**Comment by unional** [comment]
Can't repro
