### ISSUE TITLE
cli with --type-check gives: Program must be type checked before linting

### ISSUE THREAD

**Issue by aleksey-bykov** [palantir/tslint#2817]
### Bug Report

- __TSLint version__:  5.0.0-dev.0
- __TypeScript version__: 2.4.0-dev.20170518
- __Running TSLint via__: (pick one) CLI
```
node ./node_modules/tslint/bin/tslint --type-check --project ./scripts/src/tsconfig.json --config ./tslint-standard.json --format msbuild
```

#### TypeScript code being linted

```ts
// big project
```

with `tslint.json` configuration:

```json
{
    "rules": {
        "semicolon": true,
        "triple-equals": [ true, "allow-null-check" ],
        "switch-default": true,
        "no-switch-case-fall-through": false,
        "max-line-length": [ true, 300 ],
        "no-unused-expression": false,
        "no-use-before-declare": false,
        "quotemark": [ true, "single", "jsx-double" ],
        "curly": true,
        "indent": [true, "spaces"],
        "eofline": true,
        "no-inferrable-types": true,
        "no-debugger": true,
        "no-trailing-whitespace": true,
        "one-line": [ true, "check-open-brace" ],
        "align": [ true, "parameters", "statements" ],
        "no-inferred-empty-object-type": true
    }
}

```

#### Actual behavior
```
Error: Program must be type checked before linting
    at Linter.getSourceFile (c:\Theirs\aps\master\src\Intelsat.APS.Web\node_modules\tslint\lib\linter.js:193:23)
    at Linter.lint (c:\Theirs\aps\master\src\Intelsat.APS.Web\node_modules\tslint\lib\linter.js:79:31)
    at Runner.processFiles (c:\Theirs\aps\master\src\Intelsat.APS.Web\node_modules\tslint\lib\runner.js:160:20)
    at Runner.run (c:\Theirs\aps\master\src\Intelsat.APS.Web\node_modules\tslint\lib\runner.js:109:18)
    at Object.<anonymous> (c:\Theirs\aps\master\src\Intelsat.APS.Web\node_modules\tslint\lib\tslint-cli.js:139:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
#### Expected behavior

work

**Comment by ajafff** [comment]
I tried to reproduce this with current master and current typescript@next, but didn't see that error.

Anyways, that specific exception will be removed with #2773
