### ISSUE TITLE
Invalid regular expression in quotemarkRule.js

### ISSUE THREAD

**Issue by reod** [palantir/tslint#3073]
### Bug Report

- __TSLint version__: 5.5.0
- __TypeScript version__: 2.4.2
- __Running TSLint via__: CLI

When I'm executing `npx tslint -c tslint.json 'src/**/*.ts` I'm getting error:
```sh
SyntaxError: Invalid regular expression: /\\)/: Unmatched ')'
    at RegExp (<anonymous>)
    at cb (/Users/someusername/Documents/fun/i18n-manager/node_modules/tslint/lib/rules/quotemarkRule.js:116:33)
    at visitEachNode (/Users/someusername/Documents/fun/i18n-manager/node_modules/typescript/lib/typescript.js:15956:30)
    at Object.forEachChild (/Users/someusername/Documents/fun/i18n-manager/node_modules/typescript/lib/typescript.js:16089:21)
    at cb (/Users/someusername/Documents/fun/i18n-manager/node_modules/tslint/lib/rules/quotemarkRule.js:119:12)
    at visitEachNode (/Users/someusername/Documents/fun/i18n-manager/node_modules/typescript/lib/typescript.js:15956:30)
    at Object.forEachChild (/Users/someusername/Documents/fun/i18n-manager/node_modules/typescript/lib/typescript.js:16089:21)
    at cb (/Users/someusername/Documents/fun/i18n-manager/node_modules/tslint/lib/rules/quotemarkRule.js:119:12)
    at visitNode (/Users/someusername/Documents/fun/i18n-manager/node_modules/typescript/lib/typescript.js:15944:20)
    at Object.forEachChild (/Users/someusername/Documents/fun/i18n-manager/node_modules/typescript/lib/typescript.js:16145:24)
```

with `tslint.json` configuration:

```json
{
  "defaultSeverity": "error",
  "extends": ["tslint:recommended", "tslint-eslint-rules"],
  "jsRules": {},
  "rules": {
    "quotemark": [true, "single"],
    "no-empty-interface": false,
    "no-console": [false],
    "no-consecutive-blank-lines": false,
    "ordered-imports": [false],
    "arrow-parens": false,
    "trailing-comma": [false],
    "member-access": [false],
    "object-literal-sort-keys": [false],
    "align": [false],
    "member-ordering": [false],
    "interface-name": [false]
  },
  "rulesDirectory": []
}

```

#### Actual behavior
Syntax error.
#### Expected behavior
Should not throw error.

**Comment by IllusionMH** [comment]
@reod it can be reproduced now in `i18n-manager` repo (from your github profile)?

**Comment by reod** [comment]
@IllusionMH actually this issue disappeared magically during development and now even I can't reproduce it. Feel free to close my report.

**Comment by mjomble** [comment]
I found a minimal reproducible case for this error:

test.ts:
```
('a)
```

tslint.json:
```
{ "rules": { "quotemark": true } }
```

Running `tslint test.ts` gives:

```
The 'quotemark' rule threw an error in 'test.ts':
SyntaxError: Invalid regular expression: /\\)/: Unmatched ')'
...
```

Should I create a new issue or will we reopen this one?
