### ISSUE TITLE
TypeError with "Optional catch binding parameters" in TS 2.5.1

### ISSUE THREAD

**Issue by juergenzimmermann** [palantir/tslint#3154]
I'm using TSLint 5.6.0 with TS 2.5.1. I tried to use the new "Optional catch binding parameters" (see https://blogs.msdn.microsoft.com/typescript/2017/08/17/announcing-typescript-2-5-rc/#user-content-optional-catch-binding-parameters) and get a TypeError (see stacktrace below):
```
try {
    ...
}
catch {...}
```
This is the resulting stacktrace when I invoke TSLint:
```
TypeError: Cannot read property 'name' of undefined
    at cb (C:\workspace\software-engineering\mean-ohne-angular\node_modules\tslint\lib\rules\preferConstRule.js:140:65)
    at visitNode (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:11899:24)
    at Object.forEachChild (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:12145:21)
    at cb (C:\workspace\software-engineering\mean-ohne-angular\node_modules\tslint\lib\rules\preferConstRule.js:167:27)
    at visitNodes (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:11908:30)
    at Object.forEachChild (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:12084:24)
    at cb (C:\workspace\software-engineering\mean-ohne-angular\node_modules\tslint\lib\rules\preferConstRule.js:167:27)
    at cb (C:\workspace\software-engineering\mean-ohne-angular\node_modules\tslint\lib\rules\preferConstRule.js:121:29)
    at visitNodes (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:11908:30)
    at Object.forEachChild (C:\workspace\software-engineering\mean-ohne-angular\node_modules\typescript\lib\typescript.js:12159:21)
```

**Comment by ajafff** [comment]
Thank you for the report. Optional catch binding is pretty new and tslint has not yet implemented the necessary checks to not crash when encountering one (as you can see).
But there's already a PR to fix this; #3151
