### ISSUE TITLE
TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by keenwon** [palantir/tslint#3341]
### Bug Report

- __TSLint version__:  5.7.0
- __TypeScript version__: 2.5.3
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
// code snippet
```

with `tslint.json` configuration:

```json
{
  "extends": "tslint:recommended"
}
```

#### Expected behavior

```shell
$ npm run tslint

> nei7@7.0.0 tslint D:\Code\nei7
> tslint "./public/src/**/*"

TypeError: Cannot read property 'parent' of undefined
    at Object.getPreviousToken (D:\Code\nei7\node_modules\tsutils\util\util.js:106:22)
    at OneLineWalker.handleClassLikeDeclaration (D:\Code\nei7\node_modules\tslint\lib\rules\oneLineRule.js:239:43)
    at OneLineWalker.visitClassDeclaration (D:\Code\nei7\node_modules\tslint\lib\rules\oneLineRule.js:200:14)
    at OneLineWalker.SyntaxWalker.visitNode (D:\Code\nei7\node_modules\tslint\lib\language\walker\syntaxWalker.js:314:22)
    at D:\Code\nei7\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNodes (D:\Code\nei7\node_modules\typescript\lib\typescript.js:11911:30)
    at Object.forEachChild (D:\Code\nei7\node_modules\typescript\lib\typescript.js:12089:24)
    at OneLineWalker.SyntaxWalker.walkChildren (D:\Code\nei7\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:12)
    at OneLineWalker.SyntaxWalker.visitSourceFile (D:\Code\nei7\node_modules\tslint\lib\language\walker\syntaxWalker.js:228:14)
    at OneLineWalker.SyntaxWalker.visitNode (D:\Code\nei7\node_modules\tslint\lib\language\walker\syntaxWalker.js:482:22)

ERROR: public/src/app/index.ts[14, 11]: Parentheses are required around the parameters of an arrow function definition
ERROR: public/src/app/index.ts[15, 4]: file should end with a newline
ERROR: public/src/app/index.ts[10, 1]: unused expression, expected an assignment or function call
ERROR: public/src/app/index.ts[14, 3]: The key 'render' is not sorted alphabetically
ERROR: public/src/app/index.ts[1, 17]: ' should be "
ERROR: public/src/app/index.ts[2, 22]: ' should be "
ERROR: public/src/app/index.ts[3, 20]: ' should be "

```

**Comment by keenwon** [comment]
os: windows 7
cli: git bash

**Comment by ajafff** [comment]
Can you share a code snippet to reproduce? The error is thrown while handling a `class` declaration.

Is there a parse error in any of your source files?

**Comment by keenwon** [comment]
tslint checks the ".vue" files and throw the error above

```json
"script": {
  "tslint": "./public/src/**/*"
}
```

this is ok:

```json
"script": {
  "tslint": "./public/src/**/*.ts"
}
```
