### ISSUE TITLE
Using tags "existence" property in completed-docs rule causing TypeError for correct documentation containing other tags

### ISSUE THREAD

**Issue by Zbulu** [palantir/tslint#3579]
### Bug Report

- __TSLint version__: **5.8.0**
- __TypeScript version__: **2.6.1**
- __Running TSLint via__: `node_modules/.bin/tslint -c tslint.json --project . ./src/app/test.ts`

I want to add rule to tslint that when I add tag `@privateApi` to comment documentation is not required. 
#### TypeScript code being linted

```ts
/**
 *  Simple value function
 *
 * @returns It will always return 1.
 */
export function x(): number {
    return 1;
}
```

with `tslint.json` configuration:

```json
    "completed-docs": [
      true,
      {
        "functions": {
          "tags": {
            "existence": ["privateApi"]},
          "visibilities": ["exported"]
        }
      }
    ]

```

#### Actual behavior
Causes TypeError:
```
TypeError: Cannot read property 'returns' of undefined
    at TagExclusion.excludes (C:\test\node_modules\tslint\lib\rules\completed-docs\tagExclusion.js:42:47)
    at CompletedDocsWalker.checkNode (C:\test\node_modules\tslint\lib\rules\completedDocsRule.js:295:27)
    at CompletedDocsWalker.visitFunctionDeclaration (C:\test\node_modules\tslint\lib\rules\completedDocsRule.js:256:14)
    at CompletedDocsWalker.SyntaxWalker.visitNode (C:\test\node_modules\tslint\lib\language\walker\syntaxWalker.js:374:22)
    at C:\test\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitEachNode (C:\test\node_modules\typescript\lib\typescript.js:15956:30)
    at Object.forEachChild (C:\test\node_modules\typescript\lib\typescript.js:16136:24)
    at CompletedDocsWalker.SyntaxWalker.walkChildren (C:\test\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:12)
    at CompletedDocsWalker.SyntaxWalker.visitSourceFile (C:\test\node_modules\tslint\lib\language\walker\syntaxWalker.js:228:14)
    at CompletedDocsWalker.SyntaxWalker.visitNode (C:\test\node_modules\tslint\lib\language\walker\syntaxWalker.js:482:22)
```
This configuration works fine when I actually add `@privateApi' tag to comment, the following code works correctly no error or rule violation caused:
```ts
/**
 * @privateApi
 */
export function x(): number {
    return 1;
}
```

Setting **tslint.json** configuration to following value: 
```json
    "completed-docs": [
      true,
      {
        "functions": {
          "tags": {
            "content": {},
            "existence": ["privateApi"]},
          "visibilities": ["exported"]
        }
      }
    ]
```
seems seems to fix the problem however I am forced to use unnecessary empty object or I am wrong and this is required?

#### Expected behavior
Such error should not be thrown since function is correctly documented

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is deprecated** and no longer accepting pull requests other than security fixes. See #4534. ☠️ 
We recommend you instead use **[typescript-eslint](https://typescript-eslint.io)** to lint your TypeScript code with **ESLint**. ✅

👋 It was a pleasure open sourcing with you!

**Comment by JoshuaKGoldberg** [comment]
🤖 Beep boop! 👉  **TSLint is deprecated** 👈 _(#4534)_  and you should **switch to [typescript-eslint](https://typescript-eslint.io)**! 🤖 

🔒 This issue is being locked to prevent further unnecessary discussions. Thank you! 👋
