### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined for useDefaultTypeParameterRule

### ISSUE THREAD

**Issue by ameyarajwade7** [palantir/tslint#3593]
### Bug Report

- __TSLint version__: 5.8.0
- __TypeScript version__: ^2.6.2
- __Running TSLint via__: gulp-tslint
#### TypeScript code being linted

with `tslint.json` configuration:

{
  "extends": "tslint:recommended",
  "rules": {
    "object-literal-sort-keys": false,
    "trailing-comma": false
  }
}

#### Actual behavior
12:07:32.528 ERROR - Rule error during analysis of : /opt/buildagent/work/259946ecb2f73589/src/app/models/****p.ts TypeError: Cannot read property 'flags' of undefined
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at Object.isSymbolFlagSet (/opt/buildagent/work/259946ecb2f73589/.*******/*******ts-bundle/node_modules/tslint/lib/language/utils.js:159:19)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at getAliasedSymbol (/opt/buildagent/work/259946ecb2f73589/.*******/*******ts-bundle/node_modules/tslint/lib/rules/useDefaultTypeParameterRule.js:117:17)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at typeParamsFromType (/opt/buildagent/work/259946ecb2f73589/.*******/*******ts-bundle/node_modules/tslint/lib/rules/useDefaultTypeParameterRule.js:108:15)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at getArgsAndParameters (/opt/buildagent/work/259946ecb2f73589/.*******/*******ts-bundle/node_modules/tslint/lib/rules/useDefaultTypeParameterRule.js:92:23)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at cb (/opt/buildagent/work/259946ecb2f73589/.*******/*******ts-bundle/node_modules/tslint/lib/rules/useDefaultTypeParameterRule.js:50:29)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at visitNodes (/opt/buildagent/work/259946ecb2f73589/node_modules/typescript/lib/typescript.js:12699:30)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at Object.forEachChild (/opt/buildagent/work/259946ecb2f73589/node_modules/typescript/lib/typescript.js:13017:24)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at cb (/opt/buildagent/work/259946ecb2f73589/.*******/*******ts-bundle/node_modules/tslint/lib/rules/useDefaultTypeParameterRule.js:54:19)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at visitNodes (/opt/buildagent/work/259946ecb2f73589/node_modules/typescript/lib/typescript.js:12699:30)
[04:05:38][Step 5/5] 12:07:32.528 ERROR -     at Object.forEachChild (/opt/buildagent/work/259946ecb2f73589/node_modules/typescript/lib/typescript.js:12956:21)

I was Trying to run this sonarTS plugin

#### Expected behavior
Should not fail for useDefaultTypeParameterRule

**Comment by ajafff** [comment]
Can you reproduce this without any 3rd party tools? If `tslint --project tsconfig.json` results in the same exception, this is a bug in TSLint.
If not, this is caused by gulp-tslint, sonarTS or any other plugin.

To investigate this bug, we need some reproduction code.

**Comment by ameyarajwade7** [comment]
Thanks @ajafff 
 I was not able to reproduce this with only TSlint.
