### ISSUE TITLE
Builds are failing for ruleLoaderTests: "List of rules doesn't match list of tests"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4225]
Example: https://circleci.com/gh/JoshuaKGoldberg/tslint/814?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```diff
List of rules doesn't match list of tests
      + expected - actual

         "commentType"
         "completedDocs"
         "curly"
         "cyclomaticComplexity"
      +  "default"
         "deprecation"
         "encoding"
         "eofline"
         "fileHeader"
         "fileNameCasing"
         "forin"
      +  "ignoreComments"
      +  "ignoreParametersToFunctions"
         "importBlacklist"
         "importSpacing"
         "incrementDecrement"
         "indent"
         "linebreakStyle"
         "matchDefaultExportName"
         "maxClassesPerFile"
         "maxFileLineCount"
      -  "maxFunctionBodyLength"
         "maxLineLength"
         "memberAccess"
         "memberOrdering"
         "newParens"
         "oneLine"
         "oneVariablePerDeclaration"
         "onlyArrowFunctions"
         "orderedImports"
      +  "overrides"
         "preferConditionalExpression"
         "preferConst"
         "preferForOf"
         "preferFunctionOverMethod"
      
      at Function.assert.deepEqual (node_modules/chai/lib/chai/interface/assert.js:216:32)
      at Context.<anonymous> (build/test/ruleLoaderTests.js:90:23)
```

**Comment by JoshuaKGoldberg** [comment]
No longer seeing this. ✔
