### ISSUE TITLE
`no-unsafe-any` bombs on .vue single-file-templates

### ISSUE THREAD

**Issue by millimoose** [palantir/tslint#4273]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.1.2
- __Running TSLint via__: [the Vue CLI](https://github.com/vuejs/vue-cli)

#### TypeScript code being linted

The following Vue single-file template.

```vue
<script lang="ts">
//tslint:disable missing-jsdoc
import Vue from 'vue';
export default class App extends Vue {}
</script>
```

with `tslint.json` configuration:

```json
{
  "defaultSeverity": "warning",
  "extends": [
    "tslint:recommended",
    "tslint-microsoft-contrib"
  ],
  "linterOptions": {
    "exclude": [
      "node_modules/**"
    ]
  },
  "rules": {
    "quotemark": [true, "single"],
    "indent": [true, "spaces", 2],
    "interface-name": false,
    "ordered-imports": false,
    "object-literal-sort-keys": false,
    "no-consecutive-blank-lines": false,
    "export-name": [true, {"ignore-case": true}],
    "import-name": [false],
    "no-default-export": false
  }
}
```

#### Actual behavior

The following stack traces are output:

```
The 'no-use-before-declare' rule threw an error in '/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/src/App.vue':
TypeError: Cannot read property 'members' of undefined
    at resolveNameHelper (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:31434:105)
    at resolveName (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:31276:20)
    at resolveEntityName (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:32120:26)
    at getSymbolOfEntityNameOrPropertyAccessExpression (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescrip
t.js:55582:80)
    at getSymbolAtLocation (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:55669:28)
    at Object.getSymbolAtLocation (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:30310:31)
    at recur (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/tslint/lib/rules/noUseBeforeDeclareRule.js:65:54)
    at visitNode (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:15829:24)
    at Object.forEachChild (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:16208:24)
    at recur (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/tslint/lib/rules/noUseBeforeDeclareRule.js:69:27)
The 'no-unsafe-any' rule threw an error in '/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/src/App.vue':
TypeError: Cannot read property 'members' of undefined
    at resolveNameHelper (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:31434:105)
    at resolveName (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:31276:20)
    at resolveEntityName (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:32120:26)
    at getSymbolOfEntityNameOrPropertyAccessExpression (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:55582:80)
    at getSymbolAtLocation (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:55669:28)
    at Object.getSymbolAtLocation (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/typescript/lib/typescript.js:30310:31)
    at isNodeAny (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/tslint/lib/rules/noUnsafeAnyRule.js:368:26)
    at NoUnsafeAnyWalker.check (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/tslint/lib/rules/noUnsafeAnyRule.js:262:14)
    at NoUnsafeAnyWalker.visitNode (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/tslint/lib/rules/noUnsafeAnyRule.js:88:45)
    at NoUnsafeAnyWalker._this.visitNodeCallback (/mnt/c/Repos/vue-tslint-microsoft-contrib-bug/node_modules/tslint/lib/rules/noUnsafeAnyRule.js:55:71)
```

#### Expected behavior

The lint runs without errors. (Not including lint issues reported.)

#### Notes:

This refiles vuejs/vue-cli#2712.

A repository that allows reproducing the issue can be found at https://github.com/millimoose/vue-tslint-microsoft-contrib-bug.

The issue will manifest when TSLint is run through Vue CLI which enables support for linting Vue single-file templates.

**Comment by JoshuaKGoldberg** [comment]
Confirmed. Did a little digging and looks like it's this: https://github.com/Microsoft/TypeScript/issues/8136

This tip from https://github.com/angular/tsickle/issues/151 in might be helpful:

> after great debugging, this turned out to be simple: the source file being passed to tsickle wasn't type-checked so it had no symbol table references. Was a bug in my tsickle update PR.

...or it might be a red flag. I'll spend a little time debugging, but probably won't have time to find anything good.

**Comment by JoshuaKGoldberg** [comment]
Oh! @alexeagle, thank you! That actually was it!

The TypeScript program being created for lint rules has the following `fileNames`:

```
  fileNames:
   [ 'C:/Code/vue-tslint-microsoft-contrib-bug/src/shims-tsx.d.ts',
     'C:/Code/vue-tslint-microsoft-contrib-bug/src/shims-vue.d.ts' ],
```

...but the node whose type information is being requested has the following `.getSourceFile()` `fileName`:

```
fileName: 'C:/Code/vue-tslint-microsoft-contrib-bug/src/App.vue',
```

_(anecdotally, I've seen this in other type checking explorations: https://github.com/general-language-syntax/TS-GLS/issues/39..!)_

This is actually a set of larger architectural questions:
* Is there a way to provide these `.vue` files to the TypeScript program?
    * Is that a responsibility of TSLint or is this actually a bug on the Vue CLI?
* Should TSLint validate backing type-checked files before running a typed rule on a file?
    * If so, how?

**Comment by JoshuaKGoldberg** [comment]
Per #4379, a Vue-specific workaround isn't going to be able to land in TSLint core:

> Given the lack of discussion or concrete proposal here and the upcoming deprecation of TSLint in favor of ESLint (#4534), I'm going to go ahead and close this issue and related Vue-specific reports for housekeeping purposes. 
> 
> If this is still an issue for you in [typescript-eslint](https://typescript-eslint), I'd recommend filing an issue there. Best of luck!
