### ISSUE TITLE
no-unused-variable rule crashes on ES6 bare imports

### ISSUE THREAD

**Issue by felixbillon** [palantir/tslint#451]
Hie everyone,

I'm using tslint with grunt-tslint and i got an issue when i run it, since I moved on ES6 external module. I got this message : 
 
`
Fatal error: Cannot read property 'name' of undefined
`

Can I get some extra output with special parameter ? 
Anyoby have an idea ?

Tslint worked well when i was using internal module with 'module' keyword.

**Comment by adidahiya** [comment]
which version of tslint are you using?

**Comment by felixbillon** [comment]
I'm using 2.2.0-beta, then i tried with 2.3.0-beta but I got same result.

**Comment by adidahiya** [comment]
Can you post the full error output? That looks similar to an error that was fixed in 2.3.0-beta when adding support for TS 1.5 syntax.

**Comment by felixbillon** [comment]
@adidahiya of course, this is the output : 

![errortslint](https://cloud.githubusercontent.com/assets/6213796/8300057/fcabc6ec-1980-11e5-9a82-359c87fa80cb.png)

**Comment by adidahiya** [comment]
What is the minimal amount of TS code for which this error occurs? I need some more help to reproduce this bug.

**Comment by felixbillon** [comment]
I find the problem, this code cause that error : 

```
import 'jquery';
import 'signalR';
import 'angular';
//...
```

This file is name libs.ts and I use it with browserify to bundle all my vendor libs in one package.

**Comment by adidahiya** [comment]
Ok, thanks for sharing the code. There must be a bit more info included in the error output... the file where JS is throwing the error should tell you which rule is failing here. Can you try to find that?

**Comment by felixbillon** [comment]
This rule crashe "no-unused-variable".

**Comment by NickHeiner** [comment]
Hey @adidahiya, I think I'm having the same issue @felixbillon is seeing, so I'll just post here instead of opening a new issue.

**tslint.json**
```json
{
  "rules": {
    "no-unused-variable": true
  }
}
```

**sample.ts**
```
import './app/ng-app.ts'
```

The command:

```
λ tslint -f sample.ts 
/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/build/rules/noUnusedVariableRule.js:57
            if (importClause.name != null) {
                            ^
TypeError: Cannot read property 'name' of undefined
    at NoUnusedVariablesWalker.visitImportDeclaration (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/build/rules/noUnusedVariableRule.js:57:29)
    at NoUnusedVariablesWalker.SyntaxWalker.visitNode (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:41537:26)
    at /Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:41639:67
    at visitEachNode (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:5928:30)
    at Object.forEachChild (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:6070:24)
    at NoUnusedVariablesWalker.SyntaxWalker.walkChildren (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:41639:16)
    at NoUnusedVariablesWalker.SyntaxWalker.visitSourceFile (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:41412:18)
    at NoUnusedVariablesWalker.SyntaxWalker.visitNode (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:41603:26)
    at NoUnusedVariablesWalker.SyntaxWalker.walk (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:41253:18)
    at Rule.AbstractRule.applyWithWalker (/Users/nick.heiner/.nvm/v0.11.14/lib/node_modules/tslint/bin/tslint-cli.js:41768:24)
```

[TS 1.5 added the "Bare Import" syntax.](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-15) I think that tslint just isn't supporting it.

![TS docs screenshot](https://cloud.githubusercontent.com/assets/829827/8366221/1137abb2-1b61-11e5-8567-b92831537a46.png)

**Comment by adidahiya** [comment]
@NickHeiner thanks for the detailed bug report. I'll update the title of this issue.

**Comment by NickHeiner** [comment]
Great! Would you mind publishing to npm so I can pick up the bugfix?

**Comment by adidahiya** [comment]
@NickHeiner yes we're making a release now!
