### ISSUE TITLE
 The 'unnecessary-else' rule threw an error: TypeError: Cannot read property 'kind' of undefined 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#4578]
### Bug Report

- __TSLint version__: 5.14.0
- __TypeScript version__: 3.3.3333
- __Running TSLint via__: (pick one) CLI

#### TypeScript code being linted

https://github.com/Microsoft/tslint-microsoft-contrib/blob/ee64b75d68af267017e6bc861588c36f068de42c/src/functionNameRule.ts

with `tslint.json` configuration:

```json
{
    "rules": {
        "no-unnecessary-else": true
    }
}
```

#### Actual behavior

```
The 'unnecessary-else' rule threw an error in '/home/travis/build/Microsoft/tslint-microsoft-contrib/src/functionNameRule.ts':
TypeError: Cannot read property 'kind' of undefined
    at getJumpStatement (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/tslint/lib/rules/unnecessaryElseRule.js:70:17)
    at cb (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/tslint/lib/rules/unnecessaryElseRule.js:56:19)
    at visitNodes (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/typescript/lib/typescript.js:15837:30)
    at Object.forEachChild (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/typescript/lib/typescript.js:16063:24)
    at cb (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/tslint/lib/rules/unnecessaryElseRule.js:63:19)
    at visitNode (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/typescript/lib/typescript.js:15828:24)
    at Object.forEachChild (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/typescript/lib/typescript.js:16077:21)
    at cb (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/tslint/lib/rules/unnecessaryElseRule.js:63:19)
    at visitNodes (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/typescript/lib/typescript.js:15837:30)
    at Object.forEachChild (/home/travis/build/Microsoft/tslint-microsoft-contrib/node_modules/typescript/lib/typescript.js:16063:24)
```

See https://travis-ci.org/Microsoft/tslint-microsoft-contrib/jobs/505584920.

#### Expected behavior

No errors

**Comment by sandersn** [comment]
Breaks on several Definitely Typed projects as well: watchify, waitme to name two.

To repro:

1. Clone DefinitelyTyped/DefinitelyTyped
2. npm install
3. npm run lint waitme

**Comment by adidahiya** [comment]
Are DefinitelyTyped projects often using `tslint:all`? I wouldn't recommend that; it introduces breaking changes every minor version.

**Comment by sandersn** [comment]
Yeah, I'm going to change that shortly. I'm not sure why it was that way before I took over the project.

**Comment by adidahiya** [comment]
@debsmita1 any chance you could take a look at this bug report?

**Comment by debsmita1** [comment]
Sure, will look into this @adidahiya
