### ISSUE TITLE
no use before declare is broken with anonymous function export

### ISSUE THREAD

**Issue by lukeapage** [palantir/tslint#469]
Same bug as https://github.com/palantir/tslint/issues/456 but this time with the "no-use-before-declare"

```
\path\to\tslint\build\rules\noUseBeforeDeclareRule.js:50
            this.validateUsageForVariable(name.text, name.getStart());
                                              ^TypeError: Cannot read property 'text' of undefined
    at NoUseBeforeDeclareWalker.visitImportDeclaration (\path\to\tslint\build\rules\noUseBeforeDeclareRule.js:50:47)
    at NoUseBeforeDeclareWalker.SyntaxWalker.visitNode (\path\to\tslint\lib\tslint.js:41611:26)
    at NoUseBeforeDeclareWalker.ScopeAwareRuleWalker.visitNode (\path\to\tslint\lib\tslint.js:42421:40)
    at \path\to\tslint\lib\tslint.js:41707:67
    at visitEachNode (\path\to\tslint\lib\tslint.js:5928:30)
```

**Comment by adidahiya** [comment]
That error message and my testing suggests that this rule is crashing on an ES6 bare import, not an anonymous function export.

I think you're seeing the same issue as #451. There's a fix for that here: #468.

**Comment by lukeapage** [comment]
yep, sorry jumped to conclusions.

**Comment by adidahiya** [comment]
No worries. Your bug report helped me find some other bugs in `no-use-before-declare`. I've fixed them and added a regression test for default function exports here: #472
