### ISSUE TITLE
TSLint crashes with "TypeError: Cannot read property 'text' of undefined"

### ISSUE THREAD

**Issue by hazolsky** [palantir/tslint#4791]
### Bug Report

- __TSLint version__: 5.16.0
- __TypeScript version__: 3.5.2
- __Running TSLint via__: CLI

#### Reproduction using [TSLint Playground](https://palantir.github.io/tslint-playground)

https://palantir.github.io/tslint-playground/?saved=N4Igxg9gJgpiBc4IDsDOAXABAM2ZgvJgBQAOAhgE5kC28mGFAlsgOYCUBAfJgK7KzZmMKAG4AOsgmQ0WbBAgFe-GIOTDxyXESLAA2nIgA6AEaUAunVMAvAL4d83PgKFQ2GkABokmxiwQgAegDMAE0IHkwwMjxqaEZsAE9MdAALGEiUQRYeKnRGFEw0inSAd0ZUzATwikwIEuRDCSDMAFkyAGt01Bz01LIsKpzMACtUAsZUTAA3MgAbRigPTGioTHjK8MwKPjXkdAgm4IhUmBqJ7phUJfQKJLA0sHbmFmS0jLQIWfS5GtOKCAoqEakmQwAkmAhmDEIBgAA90DB+KhoXRdND0Kh5nt4MVINRqIjYFBoWYPODIdDtl9kQhMMAbJhmmQoKtmVByvlkHMtjxqct+K8YIwatIsjl+pyJDYJCAbEA

(open browser console to see the error in Playground app)

#### TypeScript code being linted

```ts
const fn = (param: string) => undefined;

const foo = undefined;
fn(({[foo.bar]: baz}) => undefined);
```

with `tslint.json` configuration:

```json
{
    "extends": ["tslint:recommended"],
    "rules": {}
}
```

#### Actual behavior

TSLint crashes with the following error
```
The 'no-inferred-empty-object-type' rule threw an error in 'test.ts':
TypeError: Cannot read property 'text' of undefined
    at emitPropertyAccessExpression (node_modules/typescript/lib/typescript.js:83320:77)
    at pipelineEmitWithHint (node_modules/typescript/lib/typescript.js:82784:32)
    at emitExpression (node_modules/typescript/lib/typescript.js:82428:13)
    at emitComputedPropertyName (node_modules/typescript/lib/typescript.js:82961:13)
    at pipelineEmitWithHint (node_modules/typescript/lib/typescript.js:82495:32)
    at emit (node_modules/typescript/lib/typescript.js:82416:13)
    at emitBindingElement (node_modules/typescript/lib/typescript.js:83289:17)
    at pipelineEmitWithHint (node_modules/typescript/lib/typescript.js:82589:32)
    at emit (node_modules/typescript/lib/typescript.js:82416:13)
    at emitNodeList (node_modules/typescript/lib/typescript.js:84775:21)
The 'deprecation' rule threw an error in 'test.ts':
TypeError: Cannot read property 'text' of undefined
    at emitPropertyAccessExpression (node_modules/typescript/lib/typescript.js:83320:77)
    at pipelineEmitWithHint (node_modules/typescript/lib/typescript.js:82784:32)
    at emitExpression (node_modules/typescript/lib/typescript.js:82428:13)
    at emitComputedPropertyName (node_modules/typescript/lib/typescript.js:82961:13)
    at pipelineEmitWithHint (node_modules/typescript/lib/typescript.js:82495:32)
    at emit (node_modules/typescript/lib/typescript.js:82416:13)
    at emitBindingElement (node_modules/typescript/lib/typescript.js:83289:17)
    at pipelineEmitWithHint (node_modules/typescript/lib/typescript.js:82589:32)
    at emit (node_modules/typescript/lib/typescript.js:82416:13)
    at emitNodeList (node_modules/typescript/lib/typescript.js:84775:21)
```

#### Expected behavior

TSLint doesn't crash.

**Comment by adidahiya** [comment]
That's not valid TypeScript. It crashes the TS compiler: http://www.typescriptlang.org/play/#code/MYewdgzgLgBAZmGBeGAKADgQwE6YLYBcM02AlmAOYCUyAfDAK5gAmApnOa8wNwBQvoSLDggQyRi3acevBKlQBvANoiQAOgBGOALpEtALwC+NJPSZsOYLlT5A

Marking as "won't fix" but open to simple PRs which make the rule implementation more resilient to parse errors

**Comment by hazolsky** [comment]
hmm, i guess it's a valid TS because it should give you an error like this: `Argument of type '({[foo.bar]: baz}: any) => void' is not assignable to parameter of type 'string'.` -- and not crashing like that.
Maybe it's worth opening an issue in TS repo 🤔
