### ISSUE TITLE
Breaking with typescript 3.7.2 in VSCode

### ISSUE THREAD

**Issue by jpike88** [palantir/tslint#4899]
### Bug Report

- __TSLint version__: 5.20.1
- __TypeScript version__: 3.7.2
- __Running TSLint via__:  VSCode

#### Actual behavior
When using workspace version ts 3.7.2, fails to work.
#### Expected behavior
Should work with 3.7.2?

**Comment by jpike88** [comment]
error in log:

```
Err 35    [11:21:8.644] Exception on executing command {"seq":9,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts","line":520,"offset":29}}:

    Could not find source file: '/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts'.

    Error: Could not find source file: '/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts'.
        at getValidSourceFile (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:130492:29)
        at Object.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:130813:73)
        at Proxy.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:71029:35)
        at IOSession.Session.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139891:83)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139249:61)
        at /Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140870:88
        at IOSession.Session.executeWithRequestId (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140861:28)
        at IOSession.Session.executeCommand (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140870:33)
        at IOSession.Session.onMessage (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140893:35)
        at Interface.<anonymous> (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:142208:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

Could not find source file is a weird error, that path DEFINITELY exists.

**Comment by JoshuaKGoldberg** [comment]
Hi @jpike88! This is the repository for TSLint, a now-deprecated linter for TypeScript. That call stack you've posted has exclusively VS Code and TypeScript-related complaints.  This line in particular:

```
Err 35    [11:21:8.644] Exception on executing command {"seq":9,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts","line":520,"offset":29}}:
```

Is a command VS Code is sending to the TypeScript language server. You'll want to work with the [VS Code](http://github.com/microsoft/vscode) and [TypeScript](https://github.com/microsoft/typescript) repositories on GitHub. Best of luck!

**Comment by JoshuaKGoldberg** [comment]
🤖 Beep boop! 👉  **TSLint is deprecated** 👈  and you should **switch to [typescript-eslint](https://typescript-eslint.io)**! 🤖 

🔒 This issue is being locked to prevent further unnecessary discussions. Thank you! 👋
