### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by szahn** [palantir/tslint#829]
Getting the following error with the default tslint.json:

# Gulp task
```js
gulp.task('checkTypeScript', function(){
    return gulp.src('app/**/*.ts').pipe(tslint()).pipe(tslint.report('prose', {emitError: false, reportLimit: 25}));
});
```

# Error
```
\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:10636
        if (!node.id)
                 ^
TypeError: Cannot read property 'id' of undefined
    at getNodeId (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:10636:18)
    at getNodeLinks (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:10899:26)
    at captureLexicalThis (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:15736:17)
    at checkThisExpression (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:15778:17)
    at checkExpressionWorker (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:18042:28)
    at checkExpressionOrQualifiedName (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:18015:42)
    at checkPropertyAccessExpressionOrQualifiedName (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:16440:24)
    at checkPropertyAccessExpression (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.
js:16434:20)
    at getSymbolOfEntityNameOrPropertyAccessExpression (\node_modules\gulp-tslint\node_modules\
tslint\lib\tslint.js:20932:25)
    at getSymbolInfo (\node_modules\gulp-tslint\node_modules\tslint\lib\tslint.js:20972:28)
```

**Comment by JKillian** [comment]
Could you give an example of the code that triggers this error? Also, what version of tslint are you using?

**Comment by adidahiya** [comment]
1. ensure that your sources compile before running TSLint
2. try running the `tslint` CLI to determine if this is caused by gulp-tslint or tslint itself
3. try the [gulp-tslint project](https://github.com/panuhorsmalahti/gulp-tslint)

**Comment by szahn** [comment]
Can't publically reveal code and it's over 10,000 lines of typescript. Sources do compile. Using gulp-tslint 2.5.1

**Comment by adidahiya** [comment]
did you try (2) above? run the `tslint` CLI to isolate the issue to a specific file?

**Comment by szahn** [comment]
Any idea how I can run tslint recursively on a folder structure? I have tons of individual files and I don't see any documentation on https://www.npmjs.com/package/tslint on how to do this to a folder.

**Comment by adidahiya** [comment]
if you're using a bash shell, it will expand globs for you. so you can just run `tslint app/**/*.ts`. you're out of luck if you're using windows, though; see #692

**Comment by szahn** [comment]
I'm on Windows. The error went away after I turned off a few rules and fixed some of the existing errors.
