### ISSUE TITLE
attempting to lint gives: TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by SomeKittens** [palantir/tslint#833]
Looks like `curlyRule.ts` is passing `node.statement` to `isStatementBraced` which is checking `node.kind`.  `kind` is a property of `node` but not `node.statement`.

Full stack trace:

```
node_modules/tslint/lib/rules/curlyRule.js:95
    return node.kind === 190;
               ^

TypeError: Cannot read property 'kind' of undefined
    at isStatementBraced (node_modules/tslint/lib/rules/curlyRule.js:95:16)
    at CurlyWalker.visitDoStatement (node_modules/tslint/lib/rules/curlyRule.js:77:14)
    at CurlyWalker.SyntaxWalker.visitNode (node_modules/tslint/lib/language/walker/syntaxWalker.js:293:22)
    at node_modules/tslint/lib/language/walker/syntaxWalker.js:455:63
    at visitEachNode (node_modules/typescript/lib/typescript.js:7421:30)
    at Object.forEachChild (node_modules/typescript/lib/typescript.js:7578:24)
    at CurlyWalker.SyntaxWalker.walkChildren (node_modules/tslint/lib/language/walker/syntaxWalker.js:455:12)
    at CurlyWalker.SyntaxWalker.visitNode (node_modules/tslint/lib/language/walker/syntaxWalker.js:449:22)
    at CurlyWalker.SyntaxWalker.walk (node_modules/tslint/lib/language/walker/syntaxWalker.js:21:14)
    at Rule.AbstractRule.applyWithWalker (node_modules/tslint/lib/language/rule/abstractRule.js:33:16)
```

**Comment by DickvdBrink** [comment]
Probably #832

**Comment by SomeKittens** [comment]
Yeah, looks like the same thing - I only looked for issues type: bug in my dupe hunt.

**Comment by DickvdBrink** [comment]
hehe, no problem :) Better to report it and have a duplicate then no report at all :)
