### ISSUE TITLE
Exception in noStringLiteralRule

### ISSUE THREAD

**Issue by egamma** [palantir/tslint#906]
tslint 3.1.1

Using a tslint.json with
```json
    "no-string-literal": true,
```

Results in the following exception when running it over this [file](https://github.com/Microsoft/vscode/blob/9983e95ca6911c237bce72d69e0246a7edf5426f/src/vs/workbench/parts/files/browser/files.contribution.ts).

```
vscode-tslint: 'Cannot read property 'getText' of undefined' while validating: file:///Users/jrieken/Code/vscode/src/vs/workbench/parts/files/browser/files.contribution.ts stacktrace: TypeError: Cannot read property 'getText' of undefined
    at NoStringLiteralWalker.visitElementAccessExpression (/Users/jrieken/Code/vscode/node_modules/tslint/lib/rules/noStringLiteralRule.js:27:36)
    at NoStringLiteralWalker.SyntaxWalker.visitNode (/Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:281:22)
    at /Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:440:63
    at visitNode (/Users/jrieken/Code/vscode/node_modules/typescript/lib/typescript.js:7409:20)
    at Object.forEachChild (/Users/jrieken/Code/vscode/node_modules/typescript/lib/typescript.js:7587:24)
    at NoStringLiteralWalker.SyntaxWalker.walkChildren (/Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:440:12)
    at NoStringLiteralWalker.SyntaxWalker.visitExpressionStatement (/Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:78:14)
    at NoStringLiteralWalker.SyntaxWalker.visitNode (/Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:290:22)
    at /Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:440:63
    at visitEachNode (/Users/jrieken/Code/vscode/node_modules/typescript/lib/typescript.js:7421:30)
```

**Comment by adidahiya** [comment]
which version of typescript are you using?

**Comment by egamma** [comment]
`tsc -v -> 1.7.3`

**Comment by JKillian** [comment]
@egamma Is it possible for you to upgrade to TSLint 3.2.1 and see if the error still persists? I believe version 3.1.1 was a little bit buggy and things should work correctly in 3.2.1.

**Comment by JKillian** [comment]
@egamma I believe this should be fixed with TSLint v3.3.0. If you continue to encounter the problem while using it, let me know and I'll reopen this.

**Comment by keithkml** [comment]
I'm getting this in TSLint 3.3.0. Unfortunately I can't paste the file as it is proprietary.

```
ERROR in ./src/app/lightshow/effects.ts
Module build failed: TypeError: Cannot read property 'getText' of undefined
    at NoStringLiteralWalker.visitElementAccessExpression (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/build/rules/noStringLiteralRule.js:40:36)
    at NoStringLiteralWalker.SyntaxWalker.visitNode (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49629:26)
    at /Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49776:67
    at visitNode (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:7197:20)
    at Object.forEachChild (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:7342:24)
    at NoStringLiteralWalker.SyntaxWalker.walkChildren (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49776:16)
    at NoStringLiteralWalker.SyntaxWalker.visitBinaryExpression (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49381:18)
    at NoStringLiteralWalker.SyntaxWalker.visitNode (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49581:26)
    at /Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49776:67
    at visitNode (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:7197:20)
    at Object.forEachChild (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:7369:24)
    at NoStringLiteralWalker.SyntaxWalker.walkChildren (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49776:16)
    at NoStringLiteralWalker.SyntaxWalker.visitExpressionStatement (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49438:18)
    at NoStringLiteralWalker.SyntaxWalker.visitNode (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49638:26)
    at /Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:49776:67
    at visitNode (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/lib/tslint.js:7197:20)
 @ ./src/app/engine/mode/mode-listening.ts 8:16-50
```

**Comment by adidahiya** [comment]
are you sure it's TSLint 3.3? this path (/Users/keith/Code/wham/whamjs-port-ts/node_modules/tslint-loader/node_modules/tslint/build/rules/noStringLiteralRule.js) suggests you are using an older version which tslint-loader depends on.

also which typescript version is in use?

**Comment by adidahiya** [comment]
Closing this for now. If you still encounter this error and can provide a minimal repro, I'd be happy to re-open the issue.
