### ISSUE TITLE
Could not find the following rules specified in the configuration: no-trailing-comma

### ISSUE THREAD

**Issue by btraut** [palantir/tslint#982]
I just pulled the latest version of tslint and gulp-tslint and I'm suddenly facing the following error:

```
[proj-path]/node_modules/tslint/lib/ruleLoader.js:29
        throw new Error(errorMessage);
        ^

Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules ([proj-path]/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint ([proj-path]/node_modules/tslint/lib/tslint.js:24:44)
    at [proj-path]/node_modules/gulp-tslint/index.js:96:34
    at respond ([proj-path]/node_modules/gulp-tslint/node_modules/rcloader/index.js:73:7)
    at respond ([proj-path]/node_modules/rcfinder/index.js:140:7)
    at [proj-path]/node_modules/rcfinder/index.js:124:17
    at [proj-path]/node_modules/rcfinder/index.js:77:13
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

Any ideas? Could this be a gulp-tslint issue?

**Comment by btraut** [comment]
Nevermind. Just found the changelog:

no-trailing-comma rule removed, it is replaced by the trailing-comma rule (#687)
